//! Project templates + scaffolding.
//!
//! `inf new` (and the editor's New Project dialog) scaffold a project directory
//! from a template: a real user cargo crate (where hand-written gameplay + the
//! P6-generated Rust will live), the `inf.toml` manifest, the content root, and
//! **a boot scene under `Content/Levels/`**.
//!
//! # The IB-7 ruling
//!
//! All four templates scaffold a boot level, and it lands where `inf cook`
//! looks. Before the island phase, two of the four scaffolded no level at all
//! and the other two scaffolded one into `<root>/Levels/` — a directory the cook
//! never opens — so **four of four produced a project `inf cook` refused**. See
//! [`Project::levels_root`](crate::Project::levels_root) for why levels are
//! content rather than a parallel root, and `inf-player`'s `first_run_path` for
//! the arm that runs `new` → `cook` → the shipped player on every template.

use std::path::{Path, PathBuf};

use crate::error::{ProjectError, Result};
use crate::manifest::ProjectManifest;

/// A first-run project template.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ProjectTemplate {
    /// Empty 3D scene.
    Blank3d,
    /// 2D side-scroller starter.
    Platformer2d,
    /// First-person starter.
    FirstPerson,
    /// Hybrid 2.5D starter: a 3D ground plane with billboarded sprites (P8.4b).
    Hybrid25d,
}

impl ProjectTemplate {
    pub fn slug(self) -> &'static str {
        match self {
            ProjectTemplate::Blank3d => "blank-3d",
            ProjectTemplate::Platformer2d => "2d-platformer",
            ProjectTemplate::FirstPerson => "first-person",
            ProjectTemplate::Hybrid25d => "hybrid-2.5d",
        }
    }

    pub fn label(self) -> &'static str {
        match self {
            ProjectTemplate::Blank3d => "Blank 3D",
            ProjectTemplate::Platformer2d => "2D Platformer",
            ProjectTemplate::FirstPerson => "First Person",
            ProjectTemplate::Hybrid25d => "Hybrid 2.5D",
        }
    }

    pub fn description(self) -> &'static str {
        match self {
            ProjectTemplate::Blank3d => "An empty 3D scene — a clean slate.",
            ProjectTemplate::Platformer2d => "A 2D side-scroller starter.",
            ProjectTemplate::FirstPerson => "A first-person starter.",
            ProjectTemplate::Hybrid25d => {
                "A 2.5D scene: a 3D ground plane with billboarded sprites."
            }
        }
    }

    pub fn from_slug(slug: &str) -> Option<Self> {
        Self::all().iter().copied().find(|t| t.slug() == slug)
    }

    pub fn all() -> &'static [ProjectTemplate] {
        &[
            ProjectTemplate::Blank3d,
            ProjectTemplate::Platformer2d,
            ProjectTemplate::FirstPerson,
            ProjectTemplate::Hybrid25d,
        ]
    }

    /// The committed starter `.inf_lvl` this template scaffolds into
    /// [`Project::levels_root`](crate::Project::levels_root) — its **boot
    /// scene**.
    ///
    /// # Every template ships one, and that is the IB-7 ruling's other half
    ///
    /// Two of the four used to return `None`, and a project with no level is a
    /// project `inf cook` refuses: *"no levels in cook — the build has no boot
    /// scene"*. Moving levels under `Content/` fixes where a level is found; it
    /// does not conjure one for a template that scaffolds none. So Blank 3D and
    /// 2D Platformer got starter scenes (`samples::blank3d_scene`,
    /// `samples::platformer_scene`), and `inf new` → `inf cook` → run is now a
    /// property of **all four**, asserted by `inf-player`'s `first_run_path`.
    ///
    /// All four payloads are generated by `inf_editor_core::samples` and blessed
    /// by `committed_sample_matches_generators`, so there is one definition of
    /// each scene in this repository and these bytes are locked to it.
    pub fn starter_level(self) -> StarterLevel {
        match self {
            ProjectTemplate::Blank3d => StarterLevel {
                file_name: "Main.inf_lvl",
                payload: include_bytes!("../../../templates/blank-3d/Blank.inf_lvl"),
                sidecar: include_bytes!("../../../templates/blank-3d/Blank.inf_lvl.toml"),
            },
            ProjectTemplate::Platformer2d => StarterLevel {
                file_name: "Main.inf_lvl",
                payload: include_bytes!("../../../templates/2d-platformer/Platformer.inf_lvl"),
                sidecar: include_bytes!("../../../templates/2d-platformer/Platformer.inf_lvl.toml"),
            },
            ProjectTemplate::FirstPerson => StarterLevel {
                file_name: "Main.inf_lvl",
                payload: include_bytes!("../../../templates/first-person/FirstPerson.inf_lvl"),
                sidecar: include_bytes!("../../../templates/first-person/FirstPerson.inf_lvl.toml"),
            },
            ProjectTemplate::Hybrid25d => StarterLevel {
                file_name: "Main.inf_lvl",
                payload: include_bytes!("../../../templates/hybrid-2.5d/Hybrid.inf_lvl"),
                sidecar: include_bytes!("../../../templates/hybrid-2.5d/Hybrid.inf_lvl.toml"),
            },
        }
    }

    /// Extra content files scaffolded **beside** the boot level, relative to the
    /// project's content root: `(relative path, bytes)`.
    ///
    /// The 2D platformer's level carries an `ActorClass` binding, and an asset
    /// GUID with no asset behind it is a player that does not move. A template's
    /// promise is a project that runs, so what the boot scene binds ships with
    /// it.
    ///
    /// # The starter character (SK1c)
    ///
    /// Every 3D template scaffolds [`STARTER_CHARACTER`] into `Characters/`, and
    /// the reason is the same promise one step further on: the New Character
    /// wizard can build a character on demand, and until this wave nothing
    /// *shipped* one — so a new 3D project's first question ("where is the
    /// player?") had no answer that did not start with a wizard.
    ///
    /// The 2D platformer does not get it. A 161-bone biped in a side-scroller is
    /// 155 KB of content an author has to notice in order to delete, and Coyote
    /// is already that template's answer to the same question.
    ///
    /// The bytes are `include_bytes!` from `samples/starter-character`, which is
    /// generated by the New Character wizard's own door and byte-locked against
    /// it — see `inf_editor_core::samples::starter_character_files`. That is why
    /// there is no crate edge here: this crate names a *path*, not `inf-anim`.
    pub fn starter_content(self) -> &'static [(&'static str, &'static [u8])] {
        match self {
            ProjectTemplate::Platformer2d => &[
                (
                    "Coyote.inf_act",
                    include_bytes!("../../../templates/2d-platformer/Coyote.inf_act"),
                ),
                (
                    "Coyote.inf_act.toml",
                    include_bytes!("../../../templates/2d-platformer/Coyote.inf_act.toml"),
                ),
            ],
            ProjectTemplate::Blank3d
            | ProjectTemplate::FirstPerson
            | ProjectTemplate::Hybrid25d => STARTER_CHARACTER,
        }
    }

    /// The example `.infini` every template scaffolds, as `(path under the
    /// content root, source text)`.
    ///
    /// Separate from [`starter_content`](Self::starter_content) rather than
    /// appended to it, and the reason is a gate: that constant's arm
    /// (`every_3d_template_ships_the_whole_starter_character`) asserts it is
    /// *exactly* the seventeen character files, so growing it would have meant
    /// loosening the one check that keeps a template from silently shipping
    /// fewer bindings than its level names.
    ///
    /// The same for all four templates, because the script it ships is about the
    /// *language* rather than about the genre: a member variable, a `begin_play`,
    /// a `tick` with arithmetic and a branch, and the two verbs every actor has.
    /// A designer's first edit to it is the arc's whole point — save the file
    /// while Simulate runs and the change is live.
    pub fn starter_script(self) -> (&'static str, &'static str) {
        (
            "Scripts/Example.infini",
            include_str!("../../../templates/scripts/Example.infini"),
        )
    }

    fn starter_lib(self, crate_name: &str) -> String {
        let doc = match self {
            ProjectTemplate::Blank3d => "an empty 3D scene",
            ProjectTemplate::Platformer2d => "a 2D platformer",
            ProjectTemplate::FirstPerson => "a first-person game",
            ProjectTemplate::Hybrid25d => "a hybrid 2.5D scene",
        };
        format!(
            "//! `{crate_name}` — gameplay for {doc}.\n\
             //!\n\
             //! Hand-written systems live here; Infini Blueprints (Phase 6) generate\n\
             //! additional Rust into this crate and stay in sync.\n\
             //!\n\
             //! Generated blueprint code lives in `src/blueprints/` and is COMMITTED,\n\
             //! not ignored — it is what cargo compiles and what ships. The editor's\n\
             //! Code tab writes it; each file carries the graph hash it came from and\n\
             //! is rewritten when that goes stale.\n\
             \n\
             pub mod blueprints;\n\
             \n\
             /// Called once when play begins.\n\
             pub fn begin_play() {{\n    \
                 // Your setup here.\n\
             }}\n\
             \n\
             /// Called every frame with the delta time in seconds.\n\
             pub fn tick(_dt: f32) {{\n    \
                 // Your per-frame logic here.\n\
             }}\n"
        )
    }
}

/// The directory under the content root that `inf new` puts `.infini` scripts
/// in. A **convention**, not a lookup — see [`crate::Project::scripts_root`] for
/// the SCRIPT1b layout ruling and why there is no manifest field.
pub const SCRIPTS_DIR: &str = "Scripts";

/// **The engine's committed starter character**, as `(path under the content
/// root, bytes)` — the seventeen files `samples/starter-character` ships, minus
/// its README and its two loose `.toml` tables.
///
/// `camera.toml` and `input.toml` are deliberately absent: both are *project*
/// tables rather than content, they have no home under `Content/`, and the
/// shipped player already falls back to the same defaults they carry. An author
/// who wants to tune either copies them out of the sample, which is what the
/// sample's README says.
///
/// The list is spelled out rather than globbed because `include_bytes!` needs a
/// literal, and `every_3d_template_ships_the_whole_starter_character` asserts it is
/// the whole set rather than whatever somebody remembered to add.
///
/// # What these bytes cost, measured (SK1c audit, M4)
///
/// **736 694 B over thirty-four files** since wave CHAR1a.2 — two committed
/// bodies, of which the two `*_Body.inf_mesh` are 311 808 B each. (It was
/// 152 408 over seventeen at SK1c, and 368 344 over seventeen once CHAR1a made
/// the body 3.8x denser.) Where that lands:
///
/// | | |
/// |---|---|
/// | a new 3D project's `Content/Characters/` | **152 408 B on disk** |
/// | its cooked `content.ipack` | **33 641 B** (wave GTA1's audit, re-measured; against 1 606 for the 2D platformer). It was 6 480 while the boot level spawned no character and the closure reached only the rig, the three clips and the machine through the controller; the level spawns one now, so the **body and its material** are in the closure too — which is the point, and 27 KB is what a player being in the build costs. The last 16 B are the audit's ground `Collider3D`, without which the pawn falls through the plane it stands on (`samples::ground_slab`) |
/// | `inf.exe` (the CLI, which scaffolds) | carries all 95 932 body bytes — searched for and found |
/// | `inf-player.exe` (**the shipped player**) | **does not carry them.** Searched for the same 64-byte probe: absent. The player links this crate and never reaches `starter_content`, so the constant is never materialised |
///
/// The SK1c ledger said "155 KB in every binary that links `inf-project`, which
/// includes the shipped player" and called it measured. It was not: a player
/// build was searched for the body's own bytes and does not contain them. The
/// cost is real for the CLI and the editor, and zero for the thing that ships to
/// a player.
pub const STARTER_CHARACTER: &[(&str, &[u8])] = &[
    (
        "Characters/Starter.inf_skel",
        include_bytes!("../../../samples/starter-character/Starter.inf_skel"),
    ),
    (
        "Characters/Starter.inf_skel.toml",
        include_bytes!("../../../samples/starter-character/Starter.inf_skel.toml"),
    ),
    (
        "Characters/Starter_Body.inf_mesh",
        include_bytes!("../../../samples/starter-character/Starter_Body.inf_mesh"),
    ),
    (
        "Characters/Starter_Body.inf_mesh.toml",
        include_bytes!("../../../samples/starter-character/Starter_Body.inf_mesh.toml"),
    ),
    (
        "Characters/Starter_Controller.inf_act",
        include_bytes!("../../../samples/starter-character/Starter_Controller.inf_act"),
    ),
    (
        "Characters/Starter_Controller.inf_act.toml",
        include_bytes!("../../../samples/starter-character/Starter_Controller.inf_act.toml"),
    ),
    (
        "Characters/Starter_Idle.inf_anim",
        include_bytes!("../../../samples/starter-character/Starter_Idle.inf_anim"),
    ),
    (
        "Characters/Starter_Idle.inf_anim.toml",
        include_bytes!("../../../samples/starter-character/Starter_Idle.inf_anim.toml"),
    ),
    (
        "Characters/Starter_Locomotion.inf_sm",
        include_bytes!("../../../samples/starter-character/Starter_Locomotion.inf_sm"),
    ),
    (
        "Characters/Starter_Locomotion.inf_sm.toml",
        include_bytes!("../../../samples/starter-character/Starter_Locomotion.inf_sm.toml"),
    ),
    (
        "Characters/Starter_Locomotion.inf_sm.txt",
        include_bytes!("../../../samples/starter-character/Starter_Locomotion.inf_sm.txt"),
    ),
    (
        "Characters/Starter_Run.inf_anim",
        include_bytes!("../../../samples/starter-character/Starter_Run.inf_anim"),
    ),
    (
        "Characters/Starter_Run.inf_anim.toml",
        include_bytes!("../../../samples/starter-character/Starter_Run.inf_anim.toml"),
    ),
    (
        "Characters/Starter_Skin.inf_mat",
        include_bytes!("../../../samples/starter-character/Starter_Skin.inf_mat"),
    ),
    (
        "Characters/Starter_Skin.inf_mat.toml",
        include_bytes!("../../../samples/starter-character/Starter_Skin.inf_mat.toml"),
    ),
    (
        "Characters/Starter_Walk.inf_anim",
        include_bytes!("../../../samples/starter-character/Starter_Walk.inf_anim"),
    ),
    (
        "Characters/Starter_Walk.inf_anim.toml",
        include_bytes!("../../../samples/starter-character/Starter_Walk.inf_anim.toml"),
    ),
    // ── THE SECOND COMMITTED BODY (wave CHAR1a.2) ────────────────────────────
    //
    // The same eight assets, the same 161 joint names in the same order, built
    // by the same wizard from proportions MEASURED off `SKM_Quinn` rather than
    // chosen. A body is generated from its rig, so a second body is a second
    // character and not a second `.inf_mesh` — see
    // `inf_editor_core::samples::starter_character_f_ids` for every number and
    // where it was read.
    //
    // Both are scaffolded, and the cost is measured rather than assumed: the
    // female set is 368 350 B over its seventeen files and the male 368 344 B,
    // so a new 3D project's `Content/Characters/` goes from 368 344 to
    // 736 694 B. The shipped player still carries none of it —
    // `starter_content` is reachable from the CLI and the editor and from
    // nothing `inf-player` links.
    (
        "Characters/Starter_F.inf_skel",
        include_bytes!("../../../samples/starter-character-f/Starter_F.inf_skel"),
    ),
    (
        "Characters/Starter_F.inf_skel.toml",
        include_bytes!("../../../samples/starter-character-f/Starter_F.inf_skel.toml"),
    ),
    (
        "Characters/Starter_F_Body.inf_mesh",
        include_bytes!("../../../samples/starter-character-f/Starter_F_Body.inf_mesh"),
    ),
    (
        "Characters/Starter_F_Body.inf_mesh.toml",
        include_bytes!("../../../samples/starter-character-f/Starter_F_Body.inf_mesh.toml"),
    ),
    (
        "Characters/Starter_F_Controller.inf_act",
        include_bytes!("../../../samples/starter-character-f/Starter_F_Controller.inf_act"),
    ),
    (
        "Characters/Starter_F_Controller.inf_act.toml",
        include_bytes!("../../../samples/starter-character-f/Starter_F_Controller.inf_act.toml"),
    ),
    (
        "Characters/Starter_F_Idle.inf_anim",
        include_bytes!("../../../samples/starter-character-f/Starter_F_Idle.inf_anim"),
    ),
    (
        "Characters/Starter_F_Idle.inf_anim.toml",
        include_bytes!("../../../samples/starter-character-f/Starter_F_Idle.inf_anim.toml"),
    ),
    (
        "Characters/Starter_F_Locomotion.inf_sm",
        include_bytes!("../../../samples/starter-character-f/Starter_F_Locomotion.inf_sm"),
    ),
    (
        "Characters/Starter_F_Locomotion.inf_sm.toml",
        include_bytes!("../../../samples/starter-character-f/Starter_F_Locomotion.inf_sm.toml"),
    ),
    (
        "Characters/Starter_F_Locomotion.inf_sm.txt",
        include_bytes!("../../../samples/starter-character-f/Starter_F_Locomotion.inf_sm.txt"),
    ),
    (
        "Characters/Starter_F_Run.inf_anim",
        include_bytes!("../../../samples/starter-character-f/Starter_F_Run.inf_anim"),
    ),
    (
        "Characters/Starter_F_Run.inf_anim.toml",
        include_bytes!("../../../samples/starter-character-f/Starter_F_Run.inf_anim.toml"),
    ),
    (
        "Characters/Starter_F_Skin.inf_mat",
        include_bytes!("../../../samples/starter-character-f/Starter_F_Skin.inf_mat"),
    ),
    (
        "Characters/Starter_F_Skin.inf_mat.toml",
        include_bytes!("../../../samples/starter-character-f/Starter_F_Skin.inf_mat.toml"),
    ),
    (
        "Characters/Starter_F_Walk.inf_anim",
        include_bytes!("../../../samples/starter-character-f/Starter_F_Walk.inf_anim"),
    ),
    (
        "Characters/Starter_F_Walk.inf_anim.toml",
        include_bytes!("../../../samples/starter-character-f/Starter_F_Walk.inf_anim.toml"),
    ),
];
/// A template's committed boot scene: the payload **and its sidecar**.
///
/// The sidecar is not decoration. `AssetDb` synthesizes a **content-derived**
/// GUID for a loose payload that has none, so a level scaffolded without one
/// gets a different identity in every project it is scaffolded into — and the
/// `ActorClass` bindings inside it name asset GUIDs that must resolve. The
/// scaffold wrote the payload alone until IB-7; this type is why it cannot
/// again.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct StarterLevel {
    /// The file name written under the project's levels root.
    pub file_name: &'static str,
    /// The `.inf_lvl` bincode payload.
    pub payload: &'static [u8],
    /// The `.inf_lvl.toml` asset sidecar (GUID, kind, content hash, deps).
    pub sidecar: &'static [u8],
}

/// The result of scaffolding: where the project was created.
#[derive(Debug, Clone)]
pub struct Scaffolded {
    pub root: PathBuf,
    pub crate_name: String,
    pub manifest: ProjectManifest,
}

/// Scaffold a new project named `name` from `template` inside `parent`. The
/// project directory is `parent/<sanitized-name>`; it must not already exist
/// (or must be empty). Returns the created root.
pub fn scaffold(parent: &Path, name: &str, template: ProjectTemplate) -> Result<Scaffolded> {
    let dir_name = sanitize_dir(name);
    let crate_name = sanitize_crate(name);
    let root = parent.join(&dir_name);

    if root.exists() && std::fs::read_dir(&root)?.next().is_some() {
        return Err(ProjectError::Other(format!(
            "{} already exists and is not empty",
            root.display()
        )));
    }

    let manifest = ProjectManifest::new(name, template.slug());
    manifest.save(&root)?;

    // User cargo crate.
    write(&root.join("Cargo.toml"), &cargo_toml(&crate_name))?;
    write(&root.join("src/lib.rs"), &template.starter_lib(&crate_name))?;
    // **`src/blueprints/` exists from day one** (Wave D), with an index that
    // compiles. `lib.rs` declares `pub mod blueprints;` above, so a project
    // scaffolded and immediately built has to find something there — an empty
    // directory would make every new project fail `cargo build` until its first
    // blueprint, which is the worst possible first impression.
    //
    // Only NEW projects get this. An existing project's hand-written `lib.rs` is
    // not edited behind its author's back; the editor's Code tab creates the
    // directory and the index on first use and the author adds the one line.
    write(
        &root.join("src/blueprints/mod.rs"),
        "// @generated by Infini Engine — edits may be overwritten.\n\
         //\n\
         // One `pub mod` per generated blueprint class. Rebuilt from the directory\n\
         // whenever the editor writes a class, so a deleted one's line goes with it.\n",
    )?;

    // Content root + the levels root INSIDE it (IB-7). Kept in git with a
    // placeholder so an empty project still round-trips through a clone.
    let content_root = root.join(&manifest.content_dir);
    let levels_root = content_root.join(&manifest.levels_dir);
    write(&content_root.join(".gitkeep"), "")?;
    write(&levels_root.join(".gitkeep"), "")?;

    // The boot scene — payload AND sidecar, so the level keeps its identity and
    // its bindings resolve. Every template ships one (IB-7).
    let level = template.starter_level();
    let level_path = levels_root.join(level.file_name);
    std::fs::create_dir_all(&levels_root)?;
    inf_asset::write_atomically(&level_path, level.payload)?;
    inf_asset::write_atomically(
        &levels_root.join(format!("{}.toml", level.file_name)),
        level.sidecar,
    )?;

    // The example script, under `Content/Scripts/` (the SCRIPT1b layout ruling —
    // see `Project::scripts_root`). Written as text through the same atomic door
    // as everything else; the asset database synthesises its sidecar on the
    // first scan, from the content hash, so the GUID is a function of the bytes.
    {
        let (rel, src) = template.starter_script();
        let path = content_root.join(rel);
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        write(&path, src)?;
    }

    // …and whatever the boot scene binds, beside it under the content root.
    for (rel, bytes) in template.starter_content() {
        let path = content_root.join(rel);
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        inf_asset::write_atomically(&path, *bytes)?;
    }

    write(&root.join(".gitignore"), GITIGNORE)?;
    write(&root.join(".gitattributes"), GITATTRIBUTES)?;
    write(
        &root.join("README.md"),
        &format!(
            "# {name}\n\nAn Infini Engine project ({}).\n\nOpen it in Infini Engine, or build the gameplay crate with `cargo build`.\n",
            template.label()
        ),
    )?;

    Ok(Scaffolded {
        root,
        crate_name,
        manifest,
    })
}

fn write(path: &Path, contents: &str) -> Result<()> {
    inf_asset::write_atomically(path, contents)?;
    Ok(())
}

fn cargo_toml(crate_name: &str) -> String {
    format!(
        "[package]\n\
         name = \"{crate_name}\"\n\
         version = \"0.1.0\"\n\
         edition = \"2021\"\n\
         \n\
         [lib]\n\
         crate-type = [\"lib\"]\n\
         \n\
         [dependencies]\n"
    )
}

const GITIGNORE: &str = "/target\n/Content/.inf/\n*.inf_lvl.autosave\ncrash-recovery.inf_lvl\n";

/// The `.gitattributes` every scaffolded project gets — **SCRIPT1b's carried
/// item 5, closed by the SCRIPT1b audit rather than carried again.**
///
/// The engine's own `.gitattributes` has had `*.infini -text` since the wave
/// that found the reason, and the ledger's carried entry said *"a user's project
/// inherits the same rule and nothing tells them so yet"*. That understated it
/// once the layout ruling landed: every template now scaffolds
/// `Content/Scripts/Example.infini` with **no committed sidecar**, so its asset
/// GUID is synthesised from its **content hash** on the first scan — and a hash
/// is over bytes. A user who commits the scaffolded project and clones it on the
/// other operating system gets git's line-ending conversion, a different byte
/// stream, a different GUID for the same program, and every `ActorClass` binding
/// pointing at nothing. Telling them is not enough when the file is already
/// there on day one; the rule ships with the project.
///
/// Scoped to what the reasoning covers: only the file kinds whose **identity is
/// their bytes** live under a user's content root. `.inf_lvl` and the other
/// binary payloads are already binary to git by content detection; `.infini` is
/// the one that reads as text and must not be treated as such.
const GITATTRIBUTES: &str = "\
# InfiniScript source is text a human writes, and `-text` is deliberate: the
# LEXER normalises CRLF, a lone CR and a byte-order mark, so what a script MEANS
# is insensitive to all three. What cannot be normalised is the file's IDENTITY
# - a `.infini` with no committed sidecar takes its asset GUID from its CONTENT
# HASH, and a hash is over bytes. Let git rewrite the line endings and the same
# program gets a different GUID on Windows than on Linux, with every level
# binding pointing at nothing.
*.infini -text
";

/// A filesystem-safe directory name (spaces → hyphens, alnum/-/_ kept).
pub fn sanitize_dir(name: &str) -> String {
    let s: String = name
        .trim()
        .chars()
        .map(|c| {
            if c.is_alphanumeric() || c == '-' || c == '_' {
                c
            } else {
                '-'
            }
        })
        .collect();
    let trimmed = s.trim_matches('-').to_string();
    if trimmed.is_empty() {
        "InfinityProject".to_string()
    } else {
        trimmed
    }
}

/// A valid `snake_case` crate name.
pub fn sanitize_crate(name: &str) -> String {
    let mut out = String::new();
    for c in name.chars() {
        if c.is_alphanumeric() {
            out.extend(c.to_lowercase());
        } else if !out.ends_with('_') {
            out.push('_');
        }
    }
    let trimmed = out.trim_matches('_').to_string();
    if trimmed.is_empty() || trimmed.chars().next().unwrap().is_numeric() {
        format!("game_{trimmed}")
    } else {
        trimmed
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn scaffold_writes_a_valid_project() {
        let parent = tempfile::tempdir().unwrap();
        let s = scaffold(parent.path(), "My Cool Game!", ProjectTemplate::Blank3d).unwrap();
        assert!(s.root.join("inf.toml").exists());
        assert!(s.root.join("Cargo.toml").exists());
        assert!(s.root.join("src/lib.rs").exists());
        // **Wave D: `lib.rs` declares the blueprints module, so the module has
        // to exist.** A scaffolded project that does not compile until its first
        // blueprint is the worst possible first impression, and the two halves
        // of that claim are one line apart on purpose.
        let lib = std::fs::read_to_string(s.root.join("src/lib.rs")).unwrap();
        assert!(lib.contains("pub mod blueprints;"), "{lib}");
        assert!(s.root.join("src/blueprints/mod.rs").exists());
        assert!(s.root.join("Content/.gitkeep").exists());
        // IB-7: the levels root is under Content/, and the pre-ruling location
        // is not created at all.
        assert!(s.root.join("Content/Levels/.gitkeep").exists());
        assert!(
            !s.root.join("Levels").exists(),
            "the pre-ruling <root>/Levels/ must not be scaffolded any more"
        );
        assert_eq!(s.crate_name, "my_cool_game");
        // The manifest reloads.
        let m = ProjectManifest::load(&s.root).unwrap();
        assert_eq!(m.name, "My Cool Game!");
        assert_eq!(m.template, "blank-3d");
        // The Cargo.toml names the sanitized crate.
        let cargo = std::fs::read_to_string(s.root.join("Cargo.toml")).unwrap();
        assert!(cargo.contains("name = \"my_cool_game\""));
    }

    /// **Every template scaffolds an InfiniScript that compiles** (SCRIPT1b
    /// clause 1), under `Content/Scripts/` where the cook can see it.
    ///
    /// Three things at once, and each has cost somebody a wave before: the file
    /// is *there* (IB-7 — a template that scaffolds content the cook cannot
    /// reach is a dead end), it is under the **content** root rather than beside
    /// the generated Rust in `src/`, and it **parses** — a scaffolded script
    /// that refuses is the first thing a new user sees.
    #[test]
    fn every_template_scaffolds_a_script_that_compiles() {
        for t in ProjectTemplate::all() {
            let parent = tempfile::tempdir().unwrap();
            let s = scaffold(parent.path(), "Scripted", *t).unwrap();
            let project = crate::Project::open(&s.root).unwrap();
            let (rel, _) = t.starter_script();
            let path = s.root.join(&s.manifest.content_dir).join(rel);
            assert!(path.exists(), "{t:?} scaffolded no script at {rel}");
            assert!(
                path.starts_with(project.scripts_root()),
                "{t:?}'s script must live under the scripts root"
            );
            assert!(
                path.starts_with(project.content_root()),
                "{t:?}'s script must be CONTENT — `inf cook` opens nothing else"
            );
            assert!(
                !s.root.join("src/scripts").exists(),
                "the rejected layout must not be scaffolded as well"
            );

            // …and it is a program, through the file door the cook uses.
            let (class, warnings) = inf_script::compile_path(&path, "script:example")
                .unwrap_or_else(|d| {
                    panic!("{t:?}'s starter script does not compile:\n{}", {
                        inf_script::render(&d)
                    })
                });
            assert!(warnings.is_empty(), "{t:?}: {warnings:?}");
            assert_eq!(class.events.len(), 2, "{t:?}: begin_play and tick");
            assert_eq!(class.variables.len(), 2, "{t:?}");

            // …and the project ships the rule that keeps that file's IDENTITY
            // stable across a clone (SCRIPT1b audit, carried item 5 closed).
            // The scaffolded script has no committed sidecar, so its GUID is its
            // content hash; git rewriting its line endings on the other
            // operating system would silently rename it.
            let attrs = std::fs::read_to_string(s.root.join(".gitattributes"))
                .unwrap_or_else(|e| panic!("{t:?} scaffolded no .gitattributes: {e}"));
            assert!(
                attrs.lines().any(|l| l.trim() == "*.infini -text"),
                "{t:?}: {attrs}"
            );
        }
    }

    #[test]
    fn refuses_a_non_empty_target() {
        let parent = tempfile::tempdir().unwrap();
        scaffold(parent.path(), "Dup", ProjectTemplate::Blank3d).unwrap();
        assert!(scaffold(parent.path(), "Dup", ProjectTemplate::Blank3d).is_err());
    }

    #[test]
    fn slug_round_trips() {
        for &t in ProjectTemplate::all() {
            assert_eq!(ProjectTemplate::from_slug(t.slug()), Some(t));
        }
    }

    /// **Every template scaffolds a boot scene, under `Content/Levels/`** — the
    /// IB-7 ruling at the scaffold door.
    ///
    /// The old version of this test asserted the opposite half by name
    /// (`assert!(ProjectTemplate::Blank3d.starter_level().is_none())`) and was
    /// green while `inf new --template blank-3d` produced a project the cook
    /// refused. A gate that pins the defect it was written beside is only useful
    /// while someone remembers it is doing that.
    #[test]
    fn every_template_scaffolds_a_boot_scene_under_content() {
        let parent = tempfile::tempdir().unwrap();
        let mut payloads: Vec<Vec<u8>> = Vec::new();
        for (i, &t) in ProjectTemplate::all().iter().enumerate() {
            let s = scaffold(parent.path(), &format!("Proj{i}"), t).unwrap();
            let levels = s
                .root
                .join(&s.manifest.content_dir)
                .join(&s.manifest.levels_dir);
            let starter = t.starter_level();
            let level = levels.join(starter.file_name);
            let side = levels.join(format!("{}.toml", starter.file_name));
            assert!(level.exists(), "{} scaffolds no boot scene", t.slug());
            assert!(
                side.exists(),
                "{} scaffolds a boot scene with no sidecar, so its GUID would be \
                 content-derived and its bindings would not resolve",
                t.slug()
            );
            let bytes = std::fs::read(&level).unwrap();
            assert!(!bytes.is_empty());
            assert_eq!(bytes, starter.payload);
            assert_eq!(std::fs::read(&side).unwrap(), starter.sidecar);
            // Whatever the boot scene binds ships beside it.
            for (rel, want) in t.starter_content() {
                let p = s.root.join(&s.manifest.content_dir).join(rel);
                assert!(p.exists(), "{}: {rel} was not scaffolded", t.slug());
                assert_eq!(&std::fs::read(&p).unwrap()[..], *want);
            }
            payloads.push(bytes);
        }
        // ANTI-VACUITY: four *different* scenes, not one file copied four times
        // — which would satisfy every assertion above.
        let mut uniq = payloads.clone();
        uniq.sort();
        uniq.dedup();
        assert_eq!(
            uniq.len(),
            ProjectTemplate::all().len(),
            "the templates do not ship distinct boot scenes"
        );
    }

    /// The 16 bytes a UUID is written as inside a bincode payload, parsed out of
    /// a sidecar's `guid = "…"` line.
    ///
    /// Hand-rolled because `inf-project` does not depend on `uuid` and must not
    /// grow a dependency to check its own committed content.
    fn sidecar_guid_bytes(sidecar: &str) -> [u8; 16] {
        let line = sidecar
            .lines()
            .find(|l| l.trim_start().starts_with("guid = "))
            .expect("the sidecar names a GUID");
        let hex: String = line
            .split('"')
            .nth(1)
            .expect("the GUID is quoted")
            .chars()
            .filter(|c| *c != '-')
            .collect();
        assert_eq!(hex.len(), 32, "not a UUID: {hex}");
        let mut out = [0u8; 16];
        for (i, b) in out.iter_mut().enumerate() {
            *b = u8::from_str_radix(&hex[i * 2..i * 2 + 2], 16).expect("hex");
        }
        out
    }

    /// **The 2D platformer's boot scene binds a blueprint, and the sidecar beside
    /// that blueprint carries THE GUID THE BINDING NAMES.**
    ///
    /// The I1 audit found this arm asserting only that the sidecar text contained
    /// `"guid = "`, and measured the consequence: the committed
    /// `Coyote.inf_act.toml` GUID could be changed to anything at all with nothing
    /// in the workspace going red — which scaffolds exactly the project the
    /// commit that added this said it prevented, *"a player that does not move"*.
    ///
    /// So the check is the identity itself. `ActorClass` is a `Uuid` written by
    /// bincode as its sixteen raw bytes, so those bytes are in the level payload
    /// verbatim, and a sidecar that names a different asset cannot contain them.
    #[test]
    fn the_platformer_template_ships_the_actor_its_level_binds() {
        let extra = ProjectTemplate::Platformer2d.starter_content();
        assert_eq!(extra.len(), 2, "the actor payload and its sidecar");
        assert_eq!(extra[1].0, "Coyote.inf_act.toml");
        let side = std::str::from_utf8(extra[1].1).unwrap();
        let guid = sidecar_guid_bytes(side);

        let level = ProjectTemplate::Platformer2d.starter_level().payload;
        assert!(
            level.windows(16).any(|w| w == guid),
            "the platformer's boot scene does not bind the actor scaffolded \
             beside it — the sidecar names {side:?}, and those bytes are nowhere \
             in the level payload, so `inf new --template 2d-platformer` \
             scaffolds a player that does not move"
        );

        // ANTI-VACUITY: a level does not contain every GUID. The nil UUID would
        // match a run of zero bytes, so the control is the real GUID with one
        // byte moved — same shape, same length, different asset.
        let mut wrong = guid;
        wrong[15] ^= 0xFF;
        assert!(
            !level.windows(16).any(|w| w == wrong),
            "a GUID the level does not bind was found in it anyway, so the \
             assertion above is not about the binding"
        );
    }

    #[test]
    fn crate_names_are_valid() {
        assert_eq!(sanitize_crate("My Game"), "my_game");
        assert_eq!(sanitize_crate("123"), "game_123");
        assert_eq!(sanitize_crate("!!!"), "game_");
    }

    /// **Every 3D template ships the starter character, and it ships all of it**
    /// (SK1c).
    ///
    /// Two claims, and the second is the one a hand-written `include_bytes!`
    /// list cannot make for itself: the table is the WHOLE sample folder. A
    /// character's assets name each other by GUID, so a scaffold missing one
    /// sidecar is a project whose rig resolves and whose clips do not — and the
    /// symptom is a character that stands still, three layers away from the
    /// list somebody forgot to add a line to.
    ///
    /// The folder is read off disk rather than mirrored here, so the two cannot
    /// drift; `README.md`, `camera.toml` and `input.toml` are the documented
    /// exceptions and are named, not pattern-matched away.
    #[test]
    fn every_3d_template_ships_the_whole_starter_character() {
        const SKIPPED: [&str; 3] = ["README.md", "camera.toml", "input.toml"];
        // **BOTH committed bodies** (wave CHAR1a.2). The union, because
        // `STARTER_CHARACTER` scaffolds both and a gate that read one folder
        // would go green on a template that shipped half a pair.
        let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../../samples");
        let dirs = [
            root.join("starter-character"),
            root.join("starter-character-f"),
        ];
        let mut on_disk: Vec<String> = Vec::new();
        for dir in &dirs {
            on_disk.extend(
                std::fs::read_dir(dir)
                    .unwrap_or_else(|e| panic!("no {}: {e}", dir.display()))
                    .filter_map(|e| e.ok())
                    .filter(|e| e.file_type().map(|t| t.is_file()).unwrap_or(false))
                    .map(|e| e.file_name().to_string_lossy().into_owned())
                    .filter(|n| !SKIPPED.contains(&n.as_str())),
            );
        }
        on_disk.sort();

        let mut shipped: Vec<String> = STARTER_CHARACTER
            .iter()
            .map(|(rel, _)| {
                rel.strip_prefix("Characters/")
                    .expect("the starter character scaffolds under Characters/")
                    .to_string()
            })
            .collect();
        shipped.sort();
        assert_eq!(
            shipped, on_disk,
            "`STARTER_CHARACTER` is not the sample folder — a character's assets \
             name each other by GUID, so a missing entry is a project whose \
             clips resolve to nothing"
        );

        // …and the bytes really are the committed ones, not a stale copy from
        // whenever the list was written. Whichever folder holds the file — the
        // scaffold flattens both into `Characters/`, so the name is the key.
        for (rel, bytes) in STARTER_CHARACTER {
            let name = rel.strip_prefix("Characters/").unwrap();
            let path = dirs
                .iter()
                .map(|d| d.join(name))
                .find(|p| p.is_file())
                .unwrap_or_else(|| panic!("{name} is in `STARTER_CHARACTER` and on no disk"));
            assert_eq!(
                &std::fs::read(&path).unwrap(),
                bytes,
                "{name} is stale in `STARTER_CHARACTER`"
            );
        }

        // Which templates get it, asserted as a partition rather than as three
        // positives: a fourth 3D template added without a line here would
        // otherwise ship nothing and nothing would say so.
        for t in ProjectTemplate::all() {
            let content = t.starter_content();
            match t {
                ProjectTemplate::Platformer2d => assert!(
                    content.iter().all(|(n, _)| n.starts_with("Coyote")),
                    "the 2D platformer scaffolds a 3D biped"
                ),
                _ => assert_eq!(
                    content.len(),
                    STARTER_CHARACTER.len(),
                    "{t:?} does not ship the starter character"
                ),
            }
        }
    }

    /// **A scaffolded 3D project really has the character on disk**, through the
    /// same `scaffold` an author gets.
    #[test]
    fn a_scaffolded_3d_project_has_a_character_in_it() {
        let parent = tempfile::tempdir().unwrap();
        let made = scaffold(parent.path(), "Proj", ProjectTemplate::Blank3d).expect("scaffold");
        let content = made.root.join(&made.manifest.content_dir);
        for (rel, bytes) in STARTER_CHARACTER {
            let path = content.join(rel);
            assert!(path.exists(), "{} was not scaffolded", path.display());
            assert_eq!(&std::fs::read(&path).unwrap(), bytes);
        }
        // The rig decodes as a rig — the scaffold's own promise, since a
        // truncated payload is a file that exists and an asset that does not.
        let rig = content.join("Characters/Starter.inf_skel");
        assert!(
            std::fs::metadata(&rig).unwrap().len() > 1024,
            "the scaffolded rig is suspiciously small"
        );
    }
}
