/**
 * Typed IPC layer — the ONLY place `invoke` is called.
 *
 * Convention (engine-wide): every backend `#[tauri::command]` gets a typed
 * wrapper here, grouped by domain. Components import these wrappers, never
 * `invoke` directly. Payload types come from `src/bindings/` — generated by
 * ts-rs from `inf_editor_core::ipc` (CI drift-checked), never hand-written.
 * Events use namespaced channels (`log://line`, `viewport://rect`,
 * `assets://changed/{id}`, …) via lib/events.ts.
 */
import { invoke } from "@tauri-apps/api/core";

import type {
  ActorGraphDto,
  BpDoc,
  BpEdit,
  DebugRunResult,
  GraphApplyResult,
  GraphRunResult,
  NodeDef,
} from "./blueprintTypes";
import type { MaterialCompileResult } from "./materialTypes";
import type { PcgBiomeResult, PcgCompileResult, PcgEvaluateResult } from "./pcgTypes";
import type { AnimClipInfoDto, AnimDeriveDto } from "./animTypes";
import type { SmClipDto, SmDoc, SmProposalDto } from "./smTypes";
import type { BlendPreviewDto, BlendSampleDto } from "./blendSpaceTypes";
import type { AssetRefDto } from "../bindings/AssetRefDto";
import type { AssetSnapshot } from "../bindings/AssetSnapshot";
import type { BiomeDefDto } from "../bindings/BiomeDefDto";
import type { BiomeSetDto } from "../bindings/BiomeSetDto";
import type { BiomeSettingsDto } from "../bindings/BiomeSettingsDto";
import type { CollectionDto } from "../bindings/CollectionDto";
import type { CaptureImportDto } from "../bindings/CaptureImportDto";
import type { CapturePreviewDto } from "../bindings/CapturePreviewDto";
import type { CaptureSettingsDto } from "../bindings/CaptureSettingsDto";
import type { CaptureStatusDto } from "../bindings/CaptureStatusDto";
import type { MaterialInstanceDto } from "../bindings/MaterialInstanceDto";
import type { MatOverridesDto } from "../bindings/MatOverridesDto";
import type { MixerConfigDto } from "../bindings/MixerConfigDto";
import type { DataAssetDto } from "../bindings/DataAssetDto";
import type { DccApplyDto } from "../bindings/DccApplyDto";
import type { DccDocDto } from "../bindings/DccDocDto";
import type { DccDragBeginDto } from "../bindings/DccDragBeginDto";
import type { DccDragDto } from "../bindings/DccDragDto";
import type { DccGizmoModeDto } from "../bindings/DccGizmoModeDto";
import type { DccPreviewDto } from "../bindings/DccPreviewDto";
import type { DccSaveDto } from "../bindings/DccSaveDto";
import type { DccGarmentDto } from "../bindings/DccGarmentDto";
import type { DccGroomDto } from "../bindings/DccGroomDto";
import type { DccGroomResultDto } from "../bindings/DccGroomResultDto";
import type { DccSelectDto } from "../bindings/DccSelectDto";
import type { DccHistoryEntryDto } from "../bindings/DccHistoryEntryDto";
import type { DccNewDto } from "../bindings/DccNewDto";
import type { GeneratedSourceDto } from "../bindings/GeneratedSourceDto";
import type { DccOrientDto } from "../bindings/DccOrientDto";
import type { DccPivotDto } from "../bindings/DccPivotDto";
import type { DccToolDto } from "../bindings/DccToolDto";
import type { DccUnwrapDto } from "../bindings/DccUnwrapDto";
import type { SkelApplyDto } from "../bindings/SkelApplyDto";
import type { SkelDocDto } from "../bindings/SkelDocDto";
import type { DataFieldDto } from "../bindings/DataFieldDto";
import type { DeleteResult } from "../bindings/DeleteResult";
import type { AddableComponentDto } from "../bindings/AddableComponentDto";
import type { DetailsDto } from "../bindings/DetailsDto";
import type { ErosionParamsDto } from "../bindings/ErosionParamsDto";
import type { DataMapExportDto } from "../bindings/DataMapExportDto";
import type { ErosionReportDto } from "../bindings/ErosionReportDto";
import type { FileEntryDto } from "../bindings/FileEntryDto";
import type { GitStatusDto } from "../bindings/GitStatusDto";
import type { HeightmapProbeDto } from "../bindings/HeightmapProbeDto";
import type { LakePreviewDto } from "../bindings/LakePreviewDto";
import type { LayoutSummary } from "../bindings/LayoutSummary";
import type { LevelSettingsDto } from "../bindings/LevelSettingsDto";
import type { GeoAnchorDto } from "../bindings/GeoAnchorDto";
import type { PackageErrorDto } from "../bindings/PackageErrorDto";
import type { PackageResultDto } from "../bindings/PackageResultDto";
import type { ProjectBootDto } from "../bindings/ProjectBootDto";
import type { ProjectInfoDto } from "../bindings/ProjectInfoDto";
import type { EditorSettings } from "../bindings/EditorSettings";
import type { GameBindingApplyDto } from "../bindings/GameBindingApplyDto";
import type { GameBindingRowDto } from "../bindings/GameBindingRowDto";
import type { EntityEditorsDto } from "../bindings/EntityEditorsDto";
import type { ViewportInteractionDto } from "../bindings/ViewportInteractionDto";
import type { ProjectSettingsDto } from "../bindings/ProjectSettingsDto";
import type { ProjectTemplateDto } from "../bindings/ProjectTemplateDto";
import type { PropValueDto } from "../bindings/PropValueDto";
import type { RecentProjectDto } from "../bindings/RecentProjectDto";
import type { RiverReportDto } from "../bindings/RiverReportDto";
import type { SearchHitDto } from "../bindings/SearchHitDto";
import type { ScriptDiagnosticDto } from "../bindings/ScriptDiagnosticDto";
import type { FoliageSettingsDto } from "../bindings/FoliageSettingsDto";
import type { SculptSettingsDto } from "../bindings/SculptSettingsDto";
import type { WaterDefaultsDto } from "../bindings/WaterDefaultsDto";
import type { WaterSettingsDto } from "../bindings/WaterSettingsDto";
import type { VoxelSettingsDto } from "../bindings/VoxelSettingsDto";
import type { VoxelStatusDto } from "../bindings/VoxelStatusDto";
import type { SearchOptsDto } from "../bindings/SearchOptsDto";
import type { SaveResultDto } from "../bindings/SaveResultDto";
import type { SceneSnapshot } from "../bindings/SceneSnapshot";
import type { SeqInterpDto } from "../bindings/SeqInterpDto";
import type { SequenceDto } from "../bindings/SequenceDto";
import type { PcgStreamStatusDto } from "../bindings/PcgStreamStatusDto";
import type { Snap2DDto } from "../bindings/Snap2DDto";
import type { Snap3DDto } from "../bindings/Snap3DDto";
import type { GizmoModeDto } from "../bindings/GizmoModeDto";
import type { GizmoSpaceDto } from "../bindings/GizmoSpaceDto";
import type { SortingLayerDto } from "../bindings/SortingLayerDto";
import type { TerrainBiomesDto } from "../bindings/TerrainBiomesDto";
import type { CharacterCreateDto } from "../bindings/CharacterCreateDto";
import type { CharacterPreviewDto } from "../bindings/CharacterPreviewDto";
import type { CharacterSpecDto } from "../bindings/CharacterSpecDto";
import type { GisImportResultDto } from "../bindings/GisImportResultDto";
import type { GisImportSettingsDto } from "../bindings/GisImportSettingsDto";
import type { GisProbeDto } from "../bindings/GisProbeDto";
import type { TerrainImportPlanDto } from "../bindings/TerrainImportPlanDto";
import type { TerrainImportResultDto } from "../bindings/TerrainImportResultDto";
import type { TerrainImportSettingsDto } from "../bindings/TerrainImportSettingsDto";
import type { CollisionLayerDto } from "../bindings/CollisionLayerDto";
import type { SpawnKind } from "../bindings/SpawnKind";
import type { SpriteSheetDto } from "../bindings/SpriteSheetDto";
import type { TilemapCellDto } from "../bindings/TilemapCellDto";
import type { TilemapDto } from "../bindings/TilemapDto";
import type { ToolModeDto } from "../bindings/ToolModeDto";
import type { ViewModeDto } from "../bindings/ViewModeDto";
import type { ViewportDrop } from "../bindings/ViewportDrop";
import type { ViewportModeDto } from "../bindings/ViewportModeDto";
import type { ViewportRect } from "../bindings/ViewportRect";

export type {
  AssetRefDto,
  AssetSnapshot,
  BiomeDefDto,
  BiomeSetDto,
  BiomeSettingsDto,
  CollectionDto,
  MaterialInstanceDto,
  MatOverridesDto,
  MixerConfigDto,
  DataAssetDto,
  DataFieldDto,
  DeleteResult,
  DetailsDto,
  EditorSettings,
  EntityEditorsDto,
  ViewportInteractionDto,
  FileEntryDto,
  GitStatusDto,
  LayoutSummary,
  PackageErrorDto,
  PackageResultDto,
  ProjectBootDto,
  ProjectInfoDto,
  ProjectTemplateDto,
  ProjectSettingsDto,
  PropValueDto,
  RecentProjectDto,
  ScriptDiagnosticDto,
  SearchHitDto,
  SearchOptsDto,
  SceneSnapshot,
  SeqInterpDto,
  SequenceDto,
  Snap2DDto,
  SortingLayerDto,
  SpawnKind,
  SpriteSheetDto,
  TerrainBiomesDto,
  TilemapCellDto,
  TilemapDto,
  ViewportDrop,
  ViewportModeDto,
  ViewportRect,
};

export const app = {
  /** Editor backend version, shown in the status bar. */
  version: (): Promise<string> => invoke<string>("app_version"),
  /** Multi-line build banner (version + git hash) for the About dialog. */
  buildInfo: (): Promise<string> => invoke<string>("app_build_info"),
};

/**
 * Embedded terminal (P5.3). A session is a real PTY in the backend; output
 * streams on `pty://output/{id}` (see lib/events.ts). Arg names are camelCase.
 */
export const pty = {
  /** Open a session in `cwd` sized `cols`×`rows`; returns the session id. */
  create: (cwd: string | null, cols: number, rows: number): Promise<string> =>
    invoke<string>("pty_create", { cwd, cols, rows }),
  write: (id: string, data: string): Promise<void> => invoke("pty_write", { id, data }),
  resize: (id: string, cols: number, rows: number): Promise<void> =>
    invoke("pty_resize", { id, cols, rows }),
  close: (id: string): Promise<void> => invoke("pty_close", { id }),
};

/** Named dock-layout presets, persisted in the app config dir (P1.2.5). */
export const layouts = {
  save: (name: string, json: string): Promise<void> => invoke("layout_save", { name, json }),
  load: (name: string): Promise<string | null> => invoke("layout_load", { name }),
  list: (): Promise<LayoutSummary[]> => invoke("layout_list"),
  delete: (name: string): Promise<boolean> => invoke("layout_delete", { name }),
};

/**
 * Native-viewport commands (P23.2a: every one takes an OPTIONAL `viewport` id).
 *
 * Omitting it means the scene viewport (`PRIMARY_VIEWPORT`) — the backend
 * resolves an absent argument to `Target::Primary` — which is why none of the
 * shell's existing call sites pass one and none of them changed. The parameter
 * is what a second viewport (P23.2b) will address; until then it is the wire's
 * way of saying "the one you already meant".
 */
export const viewport = {
  /** Create (once per id) the native engine viewport inside this window. */
  attach: (viewport?: string): Promise<void> => invoke("viewport_attach", { viewport }),
  /**
   * Report the viewport hole's rectangle in PHYSICAL pixels relative to the
   * window client area (see `toPhysicalRect` in lib/viewportRect.ts).
   */
  setRect: (rect: ViewportRect, viewport?: string): Promise<void> =>
    invoke("viewport_set_rect", { rect, viewport }),
  /**
   * Show/hide the native viewport (the shell hides it while an HTML overlay it
   * cannot measure — the palette, a dialog, the drag ghost — is open; airspace
   * rule). An overlay that measures itself uses `setRegion` instead.
   */
  setVisible: (visible: boolean, viewport?: string): Promise<void> =>
    invoke("viewport_set_visible", { visible, viewport }),
  /**
   * **Cut the open overlays' rectangles out of the native viewport** (UX2) —
   * the flash-free half of the airspace rule, so a right-click menu no longer
   * blacks out the 3D view.
   *
   * `rects` are PHYSICAL pixels relative to the window client area — the same
   * space `setRect` speaks (`toPhysicalRect` in lib/viewportRect.ts). The
   * backend subtracts the hole's origin, because it is the side that knows
   * where the native child currently is. An empty array releases the region.
   */
  setRegion: (rects: ViewportRect[], viewport?: string): Promise<void> =>
    invoke("viewport_set_region", { rects, viewport }),
  /**
   * Whether this platform can cut a hole instead of hiding (UX2): Windows can
   * (`SetWindowRgn`), macOS and Linux cannot and keep the full hide. The
   * overlay guard asks once and falls back to hiding until it knows.
   */
  cutoutSupported: (): Promise<boolean> => invoke("viewport_cutout_supported"),
  /**
   * Hand off a drag that ended over the viewport hole. Coordinates are
   * PHYSICAL pixels relative to the hole's top-left corner (HTML drag ghosts
   * die over the native window — the drop point crosses via IPC instead).
   */
  drop: (drop: ViewportDrop, viewport?: string): Promise<void> =>
    invoke("viewport_drop", { drop, viewport }),
  /** Switch the active projection (Perspective ↔ 2D ortho) (P8.2c). */
  setMode: (mode: ViewportModeDto, viewport?: string): Promise<void> =>
    invoke("viewport_set_mode", { mode, viewport }),
  /**
   * Push the pointer/camera feel from the editor preferences (Wave E): flycam
   * speed, look sensitivity, and the right-button click-vs-drag thresholds the
   * context-menu gesture is discriminated on. Every field is re-guarded at the
   * backend door.
   */
  setInteraction: (interaction: ViewportInteractionDto, viewport?: string): Promise<void> =>
    invoke("viewport_set_interaction", { interaction, viewport }),
  /**
   * Frame the current selection — what the `F` key does natively (Wave E).
   * Needed because the context menu and the palette are HTML and `F` is
   * consumed by the native child window.
   */
  focus: (viewport?: string): Promise<void> => invoke("viewport_focus", { viewport }),
  /**
   * **Frame the level's player start** (wave EDIT1, clause 2) — what the `Home`
   * key does natively, and what a level open fires so the editor opens where the
   * game begins instead of at the camera's `(14, 9, 20)` default.
   *
   * Omitting `viewport` targets EVERY viewport, unlike `focus`: the caller that
   * matters is a level open, and every open viewport is looking at the level
   * that was just replaced.
   */
  frameStart: (viewport?: string): Promise<void> =>
    invoke("viewport_frame_start", { viewport }),
  /**
   * **What the editor camera's PCG streaming is doing** (wave EDIT1, clause 5).
   * The `pcg://stream` event carries the same shape; this is the read a panel
   * does when it mounts after the last one was emitted.
   */
  pcgStreamStatus: (): Promise<PcgStreamStatusDto> => invoke("pcg_stream_status"),
  /** Push the 2D-mode grid/pixel snapping configuration to the viewport. */
  setSnap2d: (snap: Snap2DDto, viewport?: string): Promise<void> =>
    invoke("viewport_set_snap2d", { snap, viewport }),
  /** Switch the active tool (Select ↔ Sculpt terrain) (P10.2b). */
  setToolMode: (mode: ToolModeDto, viewport?: string): Promise<void> =>
    invoke("viewport_set_tool_mode", { mode, viewport }),
  /** Push the sculpt brush configuration (op / radius / strength / falloff). */
  setSculpt: (sculpt: SculptSettingsDto, viewport?: string): Promise<void> =>
    invoke("viewport_set_sculpt", { sculpt, viewport }),
  /** Push the foliage brush configuration (radius / density / kind / …) (E-P6). */
  setFoliage: (foliage: FoliageSettingsDto, viewport?: string): Promise<void> =>
    invoke("viewport_set_foliage", { foliage, viewport }),
  /**
   * Push the biome brush configuration (radius / strength / falloff / id) (P19.2).
   * `strength` is not a blend fraction — it picks which falloff contour the
   * painted biome's hard boundary lands on. `biome: 0` erases (unassigned).
   */
  setBiome: (biome: BiomeSettingsDto, viewport?: string): Promise<void> =>
    invoke("viewport_set_biome", { biome, viewport }),
  /**
   * Push the water-tool configuration (river/lake + a new body's dimensions and
   * level offset) (P20.4). The biome water hint is NOT sent from here — the tool
   * resolves it per click from the biome painted under the cursor.
   */
  setWater: (water: WaterSettingsDto, viewport?: string): Promise<void> =>
    invoke("viewport_set_water", { water, viewport }),
  /**
   * Push the voxel carve-tool configuration (brush/tunnel + radius, depth,
   * carve-or-fill, fill material) (P21.2). Both lengths are world metres and are
   * clamped non-negative backend-side.
   */
  setVoxel: (voxel: VoxelSettingsDto, viewport?: string): Promise<void> =>
    invoke("viewport_set_voxel", { voxel, viewport }),
  /**
   * The Voxel tool's live verdict (P21.2): how many volumes there are to carve,
   * which terrains could not keep a cave mouth (and the refusal text a
   * surface-crossing cut would hit, verbatim the viewport's), how many chunks are
   * unsaved, and whether this document is ALREADY carrying mouths it cannot save.
   *
   * Camera-independent, so the toolbar can answer "why would this be refused"
   * before the author makes the gesture rather than after.
   *
   * Takes no viewport id, deliberately: it answers from the DOCUMENT and the
   * process's carve store, neither of which belongs to a window (P23.2a).
   */
  voxelStatus: (): Promise<VoxelStatusDto> => invoke<VoxelStatusDto>("viewport_voxel_status"),
  /**
   * Set the transform-gizmo mode (translate/rotate/scale) (Wave 2). The viewport
   * echoes mode changes (incl. W/E/R keypresses over it) on `viewport://gizmo`.
   */
  setGizmoMode: (mode: GizmoModeDto, viewport?: string): Promise<void> =>
    invoke("viewport_set_gizmo_mode", { mode, viewport }),
  /** Switch the gizmo orientation frame (World ↔ Local) (Wave 2). */
  setGizmoSpace: (space: GizmoSpaceDto, viewport?: string): Promise<void> =>
    invoke("viewport_set_gizmo_space", { space, viewport }),
  /** Push the 3D transform-gizmo snap increments (Wave 2). */
  setSnap3d: (snap: Snap3DDto, viewport?: string): Promise<void> =>
    invoke("viewport_set_snap3d", { snap, viewport }),
  /**
   * Set the shading view mode (Lit / Unlit / Wireframe) (R-P2). `Wireframe`
   * degrades to `Unlit` in the renderer when the GPU lacks line-polygon raster.
   */
  setViewMode: (mode: ViewModeDto, viewport?: string): Promise<void> =>
    invoke("viewport_set_view_mode", { mode, viewport }),
};

/**
 * Terrain erosion bake (P10.3b). Runs the GPU hydraulic + thermal erosion
 * compute pipeline (CPU reference fallback with no adapter) over the entity's
 * terrain and commits ONE undoable height delta. `region` is an optional
 * terrain-local `[minX, minZ, maxX, maxZ]`; omit to erode the whole terrain.
 */
export const terrain = {
  erode: (
    entity: string,
    params: ErosionParamsDto,
    steps: number,
    region?: [number, number, number, number],
  ): Promise<ErosionReportDto> =>
    invoke<ErosionReportDto>("terrain_erode", { entity, params, steps, region: region ?? null }),

  /**
   * Export one erosion data map (P19.1) as a 16-bit grayscale PNG under the
   * project's `Content/DataMaps/`. `map` is `"flow" | "deposition" | "wear"`.
   *
   * The image is normalized over the exported region's own `[min, max]` — the
   * report states that range, because the stored accumulators are raw and are
   * never rescaled.
   */
  exportDataMap: (
    entity: string,
    map: "flow" | "deposition" | "wear",
    region?: [number, number, number, number],
  ): Promise<DataMapExportDto> =>
    invoke<DataMapExportDto>("terrain_export_data_map", {
      entity,
      map,
      region: region ?? null,
    }),

  // ── Terrain Import wizard (P16.4a) ───────────────────────────────────────

  /**
   * Read a heightmap's HEADER (no pixel decode) and get the settings the wizard
   * should open with. Instant even on a 16k x 16k source.
   */
  probeHeightmap: (path: string): Promise<HeightmapProbeDto> =>
    invoke<HeightmapProbeDto>("terrain_probe_heightmap", { path }),

  /**
   * The world a settings block would produce for a `width x height` source —
   * extent in METRES (the wizard divides by 1000 for its km readback) and the
   * level-0 tile counts. Pure arithmetic; recomputed on every settings edit.
   */
  importPlan: (
    width: number,
    height: number,
    settings: TerrainImportSettingsDto,
  ): Promise<TerrainImportPlanDto> =>
    invoke<TerrainImportPlanDto>("terrain_import_plan", { width, height, settings }),

  /**
   * Queue the chunked import. Returns the job id; progress arrives on
   * `assets://import` (phase `"progress"` carries `done`/`total` tiles).
   */
  import: (
    path: string,
    settings: TerrainImportSettingsDto,
    name?: string,
  ): Promise<number> =>
    invoke<number>("terrain_import", { path, settings, name: name ?? null }),

  /** Ask an in-flight import to stop; it still reports terminally. */
  cancelImport: (job: number): Promise<boolean> =>
    invoke<boolean>("terrain_import_cancel", { job }),

  /** Details of a finished `.inf_terrain` asset (the wizard's done state). */
  assetInfo: (assetId: string): Promise<TerrainImportResultDto> =>
    invoke<TerrainImportResultDto>("terrain_asset_info", { assetId }),

  /**
   * Spawn a Terrain entity that STREAMS from `assetId` (no tiles in the level).
   * One undoable edit; returns the new entity GUID.
   */
  spawnStreamed: (assetId: string): Promise<string> =>
    invoke<string>("terrain_spawn_streamed", { assetId }),

  // ── biome binding (P19.2) ────────────────────────────────────────────────

  /**
   * The biome vocabulary the Biome tool paints with, for one terrain — omit
   * `entity` for the first terrain in the level (the toolbar has no selection).
   *
   * `null` when the level has no terrain at all. An unbound (or deleted, or
   * undecodable) set is NOT an error: the DTO comes back with `biome_set: null`
   * and an empty `biomes` list, which is what the toolbar's "bind a set" hint
   * reads.
   */
  biomes: (entity?: string): Promise<TerrainBiomesDto | null> =>
    invoke<TerrainBiomesDto | null>("terrain_biomes", { entity: entity ?? null }),

  /**
   * Bind (or clear, with `asset: null`) the `.inf_biomes` set a terrain's painted
   * biome ids name — ONE undo step. `false` when nothing changed.
   */
  setBiomeSet: (entity: string, asset: string | null): Promise<boolean> =>
    invoke<boolean>("terrain_set_biome_set", { entity, asset }),
};

/**
 * The GIS import door (IB-3): probe a vector source, get the settings the
 * wizard should open on, import it.
 *
 * All three go through `inf_gis::import` in Ring 0 — the same door `inf gis`
 * uses headlessly — so the wizard makes no import decision of its own. The
 * `digest` on the result is the same number `inf gis plan` prints.
 */
export const gis = {
  /**
   * What is inside a Shapefile or GeoJSON, BEFORE the level needs an anchor —
   * fields with their coverage and a sample value, the `.prj`'s CRS and where
   * it came from, the layer's centre on Earth and the UTM zone to anchor in.
   *
   * `sourceCrs` empty reads the `.prj`; a file with neither is a refusal
   * naming the remedy rather than a guess.
   */
  probe: (path: string, sourceCrs = ""): Promise<GisProbeDto> =>
    invoke<GisProbeDto>("gis_probe", { path, sourceCrs }),

  /**
   * The defaults for a probed source: the layer kind its geometry suggests,
   * and the author's own remembered entity cap (IB-14).
   */
  suggestedSettings: (
    probe: GisProbeDto,
    maxEntities: number,
  ): Promise<GisImportSettingsDto> =>
    invoke<GisImportSettingsDto>("gis_suggested_settings", { probe, maxEntities }),

  /**
   * Import. Spawns the layer's centrelines or boundaries, plus whichever of
   * the road surface, the land-cover paint and the footprint bake was asked
   * for. Emits `world://delta` and `assets://changed`.
   */
  import: (
    path: string,
    settings: GisImportSettingsDto,
  ): Promise<GisImportResultDto> =>
    invoke<GisImportResultDto>("gis_import", { path, settings }),
};

/**
 * Hydrology authoring (P20.4): the biome-hint defaults, the lake fill preview,
 * the placements (each ONE undo step) and the river verdict.
 *
 * The native viewport performs the same placements directly on the document it
 * shares, so these are the entry point for everything that is NOT a viewport
 * gesture — the command palette, a panel, a test.
 */
export const water = {
  /** What a click at a world point suggests, incl. the biome `water_hint`. */
  defaults: (x: number, z: number): Promise<WaterDefaultsDto> =>
    invoke<WaterDefaultsDto>("water_defaults", { x, z }),
  /** Where a still-water level lands on the ground inside a rectangle. */
  lakePreview: (
    centerX: number,
    centerZ: number,
    halfX: number,
    halfZ: number,
    levelM: number,
    resolution: number,
  ): Promise<LakePreviewDto> =>
    invoke<LakePreviewDto>("water_lake_preview", {
      centerX,
      centerZ,
      halfX,
      halfZ,
      levelM,
      resolution,
    }),
  /** Place a lake — ONE undo step. Returns the new entity GUID. */
  createLake: (
    centerX: number,
    centerY: number,
    centerZ: number,
    halfX: number,
    halfZ: number,
    levelM: number,
  ): Promise<string> =>
    invoke<string>("water_create_lake", {
      centerX,
      centerY,
      centerZ,
      halfX,
      halfZ,
      levelM,
    }),
  /**
   * Place a river — ONE undo step. `points` is a FLAT `[x, y, z, …]` array of at
   * least two world-space control points.
   */
  createRiver: (
    points: number[],
    widthM: number,
    depthM: number,
    flowMS: number,
  ): Promise<string> =>
    invoke<string>("water_create_river", { points, widthM, depthM, flowMS }),
  /** Append a world-space control point to a river — ONE undo step. */
  appendRiverPoint: (entity: string, x: number, y: number, z: number): Promise<boolean> =>
    invoke<boolean>("water_append_river_point", { entity, x, y, z }),
  /** Rewrite a river's width / depth / flow profile — ONE undo step. */
  setRiverProfile: (
    entity: string,
    widthStartM: number,
    widthEndM: number,
    depthStartM: number,
    depthEndM: number,
    flowMS: number,
  ): Promise<boolean> =>
    invoke<boolean>("water_set_river_profile", {
      entity,
      widthStartM,
      widthEndM,
      depthStartM,
      depthEndM,
      flowMS,
    }),
  /**
   * The river tool's verdict: the two COOK advisories re-run (so the tool says
   * what the build will) plus the terrain-aware bed conflicts only the editor
   * can make.
   */
  riverReport: (entity: string): Promise<RiverReportDto> =>
    invoke<RiverReportDto>("water_river_report", { entity }),
};

/**
 * Per-project editor settings (P8.2c): pixels-per-unit for 2D pixel snapping,
 * persisted under `<content-root>/.infinity/settings.toml`. `set` returns the
 * normalized values.
 */
export const projectSettings = {
  get: (): Promise<ProjectSettingsDto> => invoke<ProjectSettingsDto>("project_settings_get"),
  set: (settings: ProjectSettingsDto): Promise<ProjectSettingsDto> =>
    invoke<ProjectSettingsDto>("project_settings_set", { settings }),
};

/**
 * App-level (per-user) editor preferences (Wave E): theme, autosave period,
 * camera + viewport-interaction feel, snap/foliage brush defaults and keybinding
 * overrides, persisted as `<app config>/editor-settings.toml`.
 *
 * `get` REJECTS on a corrupt file rather than resolving to defaults (C4-38) —
 * the store keeps its in-memory values and surfaces the message. `set` returns
 * the NORMALIZED settings (every scalar finite and in range); the store
 * hydrates from the reply, never from what it sent.
 */
export const editorSettings = {
  get: (): Promise<EditorSettings> => invoke<EditorSettings>("editor_settings_get"),
  set: (settings: EditorSettings): Promise<EditorSettings> =>
    invoke<EditorSettings>("editor_settings_set", { settings }),
};

/**
 * The **game's** binding table (island wave I5) — the controls a player uses,
 * not the editor's chords.
 *
 * Both doors are projections of `inf_ui::bindings`, which is the same source the
 * in-game settings dialog reads: there is no table in TypeScript, deliberately.
 * `apply` with `swap = false` reports a conflict and changes NOTHING, so a panel
 * that ignores `conflicts` cannot silently steal a key from another control;
 * with `swap = true` the key is taken off exactly the rows that owned it.
 */
export const gameBindings = {
  table: (overrides: Record<string, string>): Promise<GameBindingRowDto[]> =>
    invoke<GameBindingRowDto[]>("game_bindings_table", { overrides }),
  apply: (
    overrides: Record<string, string>,
    row: string,
    token: string,
    swap: boolean,
  ): Promise<GameBindingApplyDto> =>
    invoke<GameBindingApplyDto>("game_binding_apply", { overrides, row, token, swap }),
};

/**
 * Scene / world binding (Phase 3). The authoritative ECS world lives in the
 * backend; these mutate it and the frontend re-syncs from the returned value or
 * the `world://delta` event. Arg names are camelCase (Tauri maps to snake_case).
 */
export const scene = {
  snapshot: (): Promise<SceneSnapshot> => invoke<SceneSnapshot>("scene_snapshot"),
  details: (): Promise<DetailsDto> => invoke<DetailsDto>("scene_details"),
  /**
   * **Which editors can open these entities** (Wave E). Defaults to the current
   * selection when `guids` is null.
   *
   * The only way the frontend can learn an entity's mesh / rig / material /
   * blueprint: those links are `#[reflect(ignore)]`, so they never appear in the
   * reflection-driven Details grid. Each row carries either an asset link or a
   * named `no_editor_reason` — see `lib/objectEditors.ts`, the one resolver.
   */
  entityEditors: (guids: string[] | null = null): Promise<EntityEditorsDto[]> =>
    invoke<EntityEditorsDto[]>("scene_entity_editors", { guids }),
  create: (kind: SpawnKind, parent: string | null): Promise<string> =>
    invoke<string>("scene_create", { kind, parent }),
  delete: (guids: string[]): Promise<void> => invoke("scene_delete", { guids }),
  /**
   * Duplicate roots (defaults to the current selection) as one undo step — fresh
   * GUIDs, hierarchy preserved, copies placed as siblings. Resolves to the new
   * root GUIDs (already selected backend-side).
   */
  duplicate: (guids: string[] | null = null): Promise<string[]> =>
    invoke<string[]>("scene_duplicate", { guids }),
  /** Copy roots (defaults to selection) into the backend clipboard; resolves to the count. */
  copy: (guids: string[] | null = null): Promise<number> => invoke<number>("scene_copy", { guids }),
  /** Cut = copy + delete (one Delete undo step); resolves to the count captured. */
  cut: (guids: string[] | null = null): Promise<number> => invoke<number>("scene_cut", { guids }),
  /** Paste the clipboard with fresh GUIDs; resolves to the new root GUIDs (selected). */
  paste: (): Promise<string[]> => invoke<string[]>("scene_paste"),
  /** The path the current level last opened from / saved to (null = untitled). */
  currentPath: (): Promise<string | null> => invoke<string | null>("scene_current_path"),
  /**
   * The guid of the level's player-controlled character, or null when it has
   * none (wave GTA1). Answered by the runtime's own `camera_subject`, so it
   * predicts exactly what Play is about to do: with no pawn the player process
   * keeps its overhead view and nothing responds to input.
   */
  playerPawn: (): Promise<string | null> => invoke<string | null>("scene_player_pawn"),
  rename: (guid: string, name: string): Promise<void> => invoke("scene_rename", { guid, name }),
  reparent: (guid: string, parent: string | null): Promise<boolean> =>
    invoke<boolean>("scene_reparent", { guid, parent }),
  setVisible: (guid: string, visible: boolean): Promise<void> =>
    invoke("scene_set_visible", { guid, visible }),
  select: (guids: string[], additive: boolean): Promise<void> =>
    invoke("scene_select", { guids, additive }),
  setProperty: (
    guids: string[],
    typePath: string,
    field: string,
    value: PropValueDto,
  ): Promise<DetailsDto> =>
    invoke<DetailsDto>("scene_set_property", { guids, typePath, field, value }),
  resetProperty: (guids: string[], typePath: string, field: string): Promise<DetailsDto> =>
    invoke<DetailsDto>("scene_reset_property", { guids, typePath, field }),
  /** The components the user may "+ Add Component" (E-P1). */
  listAddableComponents: (): Promise<AddableComponentDto[]> =>
    invoke<AddableComponentDto[]>("scene_list_addable_components"),
  /** Add a Default `typePath` component to `guids` (or the selection) as one undo step (E-P1). */
  addComponent: (typePath: string, guids: string[] | null = null): Promise<DetailsDto> =>
    invoke<DetailsDto>("scene_add_component", { guids, typePath }),
  /** Remove `typePath` from a single entity (E-P1). */
  removeComponent: (guid: string, typePath: string): Promise<DetailsDto> =>
    invoke<DetailsDto>("scene_remove_component", { guid, typePath }),
  /** The default element for the list at `path` on `typePath`'s component (ListField "add", E-P1). */
  listDefault: (typePath: string, path: string): Promise<PropValueDto> =>
    invoke<PropValueDto>("scene_list_default", { typePath, path }),
  undo: (): Promise<void> => invoke("scene_undo"),
  redo: (): Promise<void> => invoke("scene_redo"),
  /** Save to `path`, or a default quicksave when omitted. */
  save: (path: string | null = null): Promise<SaveResultDto> =>
    invoke("scene_save", { path }),
  open: (path: string | null = null): Promise<SceneSnapshot> =>
    invoke<SceneSnapshot>("scene_open", { path }),
  newScene: (): Promise<SceneSnapshot> => invoke<SceneSnapshot>("scene_new"),
  /** The level's file-level settings (gravity / sim rate / render block) for the World Settings panel. */
  getSettings: (): Promise<LevelSettingsDto> => invoke<LevelSettingsDto>("scene_get_settings"),
  /** Replace the level settings as one undo step (World Settings panel; debounced). */
  setSettings: (settings: LevelSettingsDto): Promise<void> =>
    invoke("scene_set_settings", { settings }),
  /**
   * Where on Earth world (0,0,0) is (Wave G).
   *
   * Its own pair rather than a field on the settings DTO, matching the schema
   * decision: the anchor is document provenance, not a simulation parameter.
   */
  getGeoAnchor: (): Promise<GeoAnchorDto> => invoke<GeoAnchorDto>("scene_get_geo_anchor"),
  /** Replace the geo-anchor. Rejects an anchor that cannot be transformed through. */
  setGeoAnchor: (anchor: GeoAnchorDto): Promise<void> =>
    invoke("scene_set_geo_anchor", { anchor }),
  /** Write the crash-recovery file if there are unsaved changes. */
  autosave: (): Promise<void> => invoke("scene_autosave"),
  /** Spawn a Content-Drawer asset dropped over the viewport (P4.4). */
  spawnAsset: (assetId: string): Promise<string> =>
    invoke<string>("scene_spawn_asset", { assetId }),
  /**
   * Apply a material asset's PBR parameters to entities (P7.1). `targets`
   * defaults to the current selection. Resolves to how many were updated.
   */
  applyMaterial: (assetId: string, targets: string[] | null = null): Promise<number> =>
    invoke<number>("scene_apply_material", { assetId, targets }),
  /**
   * Bind a `.inf_act` blueprint-class asset to entities (P9.5). Sets each
   * target's `ActorClass` link to the asset GUID; `targets` defaults to the
   * current selection. Resolves to how many entities were (re)bound.
   */
  applyActor: (assetId: string, targets: string[] | null = null): Promise<number> =>
    invoke<number>("scene_apply_actor", { assetId, targets }),
  /**
   * Apply a texture's sprite-sheet slice to entities (P8.2a). `slice` is a
   * resolved slice name (grid cells are index-named "0","1",…; manual rects use
   * their names). `resizeToSlice` sets the quad size from the slice's pixel
   * aspect. `targets` defaults to the current selection; resolves to how many
   * entities were updated.
   */
  applySpriteSlice: (
    assetId: string,
    slice: string,
    resizeToSlice: boolean,
    targets: string[] | null = null,
  ): Promise<number> =>
    invoke<number>("scene_apply_sprite_slice", { assetId, slice, targets, resizeToSlice }),
};

/**
 * Tilemap painting (P8.2b). `get` projects the selected entity's tilemap for
 * the Tilemap paint panel; `paint` applies one stroke (mouse-down→up batch or a
 * bounded flood-fill) as a single undo step. Tile indices are 1-based atlas
 * cells (`0` erases). Arg names are camelCase (Tauri maps to snake_case).
 */
export const tilemap = {
  get: (entity: string): Promise<TilemapDto | null> =>
    invoke<TilemapDto | null>("tilemap_get", { entity }),
  paint: (entity: string, cells: TilemapCellDto[]): Promise<number> =>
    invoke<number>("tilemap_paint", { entity, cells }),
};

/**
 * Sprite-sheet slicing (P8.2a). A texture asset's slice model is persisted into
 * its sidecar; the Sprite Sheet panel reads it, edits it live, and saves.
 */
export const texture = {
  getSlices: (id: string): Promise<SpriteSheetDto> =>
    invoke<SpriteSheetDto>("texture_get_slices", { id }),
  setSlices: (slices: SpriteSheetDto): Promise<void> =>
    invoke("texture_set_slices", { slices }),
};

/**
 * Sorting-layer registry (P8.2a): a per-project map of `i32` layer ids → names,
 * managed from the "Sorting Layers" dialog. `set` returns the normalized list.
 */
export const layers = {
  get: (): Promise<SortingLayerDto[]> => invoke<SortingLayerDto[]>("layers_get"),
  set: (rows: SortingLayerDto[]): Promise<SortingLayerDto[]> =>
    invoke<SortingLayerDto[]>("layers_set", { layers: rows }),
};

/**
 * Collision-layer name registry (P12.1): a per-project map of the 32 collision
 * bits → names, the sibling of {@link layers}. `set` returns the normalized list.
 * A named-bitmask Details widget driven by this is a documented follow-up; today
 * the `Collider*` masks are edited as raw `u32`.
 */
export const collisionLayers = {
  get: (): Promise<CollisionLayerDto[]> =>
    invoke<CollisionLayerDto[]>("collision_layers_get"),
  set: (rows: CollisionLayerDto[]): Promise<CollisionLayerDto[]> =>
    invoke<CollisionLayerDto[]>("collision_layers_set", { layers: rows }),
};

/**
 * Sequencer seed (P11.4): project-local property-track timelines under
 * `.infinity/sequences/`. `scrub` previews sampled values in the viewport WITHOUT
 * dirtying the scene (restored by `scrubStop`); it is refused while Simulate runs.
 * `keySet` / `captureKey` mutate the sequence file (non-undoable v1) and emit
 * `seq://changed`. `captureKey` reads the entity's live scalar into a key.
 */
export const sequencer = {
  list: (): Promise<string[]> => invoke<string[]>("seq_list"),
  get: (name: string): Promise<SequenceDto | null> =>
    invoke<SequenceDto | null>("seq_get", { name }),
  save: (sequence: SequenceDto): Promise<SequenceDto> =>
    invoke<SequenceDto>("seq_save", { sequence }),
  delete: (name: string): Promise<void> => invoke("seq_delete", { name }),
  keySet: (
    name: string,
    target: string,
    path: string,
    t: number,
    value: number,
    interp: SeqInterpDto,
  ): Promise<SequenceDto> =>
    invoke<SequenceDto>("seq_key_set", { name, target, path, t, value, interp }),
  captureKey: (name: string, target: string, path: string, t: number): Promise<SequenceDto> =>
    invoke<SequenceDto>("seq_capture_key", { name, target, path, t }),
  scrub: (name: string, t: number): Promise<void> => invoke("seq_scrub", { name, t }),
  scrubStop: (): Promise<void> => invoke("seq_scrub_stop"),
};

/**
 * Asset system / Content Drawer (Phase 4). The asset database lives in the
 * backend under the project content root; the store loads `assets_snapshot`
 * and re-fetches on the `assets://changed` event. Thumbnails are lazy PNG
 * data-URLs. Arg names are camelCase (Tauri maps to snake_case).
 */
export const assets = {
  snapshot: (): Promise<AssetSnapshot> => invoke<AssetSnapshot>("assets_snapshot"),
  /** Assets that reference `id` (Show References / delete warning). */
  references: (id: string): Promise<AssetRefDto[]> =>
    invoke<AssetRefDto[]>("asset_references", { id }),
  /** A PNG data-URL thumbnail, or null for icon-only kinds / no GPU. */
  thumbnail: (id: string): Promise<string | null> =>
    invoke<string | null>("asset_thumbnail", { id }),
  /** Queue external files for import; progress arrives on `assets://import`. */
  import: (sources: string[], destFolder: string | null = null): Promise<number[]> =>
    invoke<number[]>("asset_import", { sources, destFolder }),
  /** Create a new authored asset (Phase 4.4: "material"). Returns the GUID. */
  create: (kind: string, folder: string | null = null, name: string | null = null): Promise<string> =>
    invoke<string>("asset_create", { kind, folder, name }),
  /** Create a material instance overriding a parent material (P7.4). */
  createMaterialInstance: (parentId: string, name: string | null = null): Promise<string> =>
    invoke<string>("asset_create_material_instance", { parentId, name }),
  /** Load a material instance for the override editor (parent + resolved baseline + overrides) (E-P2). */
  getMaterialInstance: (id: string): Promise<MaterialInstanceDto> =>
    invoke<MaterialInstanceDto>("asset_get_material_instance", { id }),
  /** Save edited overrides onto a material instance (E-P2). */
  saveMaterialInstance: (id: string, overrides: MatOverridesDto): Promise<void> =>
    invoke("asset_save_material_instance", { id, overrides }),
  /** Load a `.inf_biomes` for the inline biome-set editor (P19.2). */
  getBiomeSet: (id: string): Promise<BiomeSetDto> =>
    invoke<BiomeSetDto>("asset_get_biome_set", { id }),
  /**
   * Save an edited `.inf_biomes` (P19.2). The backend VALIDATES — duplicate ids,
   * the reserved id 0, a blank name or an out-of-range splat layer reject the
   * save and leave the file alone — so a rejection arrives as a thrown message.
   */
  saveBiomeSet: (id: string, set: BiomeSetDto): Promise<void> =>
    invoke("asset_save_biome_set", { id, set }),
  /** Delete; when still referenced (and not forced) returns the blockers. */
  delete: (id: string, force = false): Promise<DeleteResult> =>
    invoke<DeleteResult>("asset_delete", { id, force }),
  rename: (id: string, name: string): Promise<void> => invoke("asset_rename", { id, name }),
  duplicate: (id: string): Promise<string> => invoke<string>("asset_duplicate", { id }),
  setTags: (id: string, tags: string[]): Promise<void> => invoke("asset_set_tags", { id, tags }),
  /** Load a data asset (struct/enum/table) for editing; null if not a data kind. */
  data: (id: string): Promise<DataAssetDto | null> =>
    invoke<DataAssetDto | null>("asset_data", { id }),
  dataSave: (dataAsset: DataAssetDto): Promise<void> =>
    invoke("asset_data_save", { dataAsset }),
  tableImport: (id: string, source: string): Promise<void> =>
    invoke("asset_table_import", { id, source }),
  rustSource: (id: string): Promise<string> => invoke<string>("asset_rust_source", { id }),
};

/**
 * Audio mixer (E-P9): the project's named-bus `inf_audio::MixerConfig`, persisted
 * at `<project_root>/.infinity/mixer.toml`. `save` validates (unique non-empty
 * names, a present + rootless `master`, existing parents, no cycles), persists,
 * live-applies to a running Simulate session, and broadcasts on
 * `audio://mixer-changed`. Arg name is camelCase (Tauri maps to snake_case).
 */
export const audio = {
  mixerGet: (): Promise<MixerConfigDto> => invoke<MixerConfigDto>("mixer_get"),
  mixerSave: (config: MixerConfigDto): Promise<void> => invoke("mixer_save", { config }),
};

/**
 * Named content collections (E-P8): user-defined, persisted groupings of assets
 * stored at `<project_root>/.infinity/collections.toml`. Every mutation returns
 * the full updated list and also broadcasts on `collections://changed`. Names
 * are unique + non-empty (the backend validates). Arg names are camelCase.
 */
export const collections = {
  list: (): Promise<CollectionDto[]> => invoke<CollectionDto[]>("collections_list"),
  create: (name: string): Promise<CollectionDto[]> =>
    invoke<CollectionDto[]>("collections_create", { name }),
  rename: (oldName: string, newName: string): Promise<CollectionDto[]> =>
    invoke<CollectionDto[]>("collections_rename", { old: oldName, new: newName }),
  delete: (name: string): Promise<CollectionDto[]> =>
    invoke<CollectionDto[]>("collections_delete", { name }),
  add: (name: string, id: string): Promise<CollectionDto[]> =>
    invoke<CollectionDto[]>("collections_add", { name, id }),
  remove: (name: string, id: string): Promise<CollectionDto[]> =>
    invoke<CollectionDto[]>("collections_remove", { name, id }),
};

/**
 * Project system (Phase 5.5). Opening/creating a project re-roots the asset
 * database and emits `project://changed`. Arg names are camelCase.
 */
export const project = {
  templates: (): Promise<ProjectTemplateDto[]> =>
    invoke<ProjectTemplateDto[]>("project_templates"),
  recent: (): Promise<RecentProjectDto[]> => invoke<RecentProjectDto[]>("project_recent"),
  current: (): Promise<ProjectInfoDto | null> =>
    invoke<ProjectInfoDto | null>("project_current"),
  newProject: (parent: string, name: string, template: string): Promise<ProjectInfoDto> =>
    invoke<ProjectInfoDto>("project_new", { parent, name, template }),
  open: (root: string): Promise<ProjectInfoDto> => invoke<ProjectInfoDto>("project_open", { root }),
  /**
   * The `.inf_lvl` path a cooked build of this project would boot into, or null
   * (wave GTA1). The cook's own rule -- the lowest-GUID level -- read off the
   * same asset database, so "the level the editor opens" and "the level the
   * build starts in" are the same sentence.
   */
  bootLevel: (): Promise<string | null> => invoke<string | null>("project_boot_level"),
  /**
   * Open the project the application boots with when it was launched with none
   * (wave CERT1), or null for the start screen. `INF_BOOT_PROJECT`, then the
   * `boot_project` pin (the last project opened), then the showcase island
   * discovered beside the checkout -- `inf_project::boot::resolve` is the whole
   * rule and this is its only caller.
   *
   * It opens through `apply_open`, so `project://changed` fires and the boot
   * level opens exactly as it does from the start screen. Calling it while a
   * project is already open is a no-op that returns null.
   */
  bootDefault: (): Promise<ProjectBootDto | null> =>
    invoke<ProjectBootDto | null>("project_boot_default"),
  /**
   * Make the OPEN project the one the application boots on (CERT1 audit
   * ruling) — the deliberate pin, which outranks the showcase island and which
   * an ordinary project open never overwrites. Resolves to the phrase for the
   * rung that will answer at the next launch.
   */
  setDefault: (): Promise<string> => invoke<string>("project_set_default"),
  /**
   * Forget the deliberate default, so the showcase island (or, on a machine
   * without one, the last project opened) answers again. Resolves to the phrase
   * for what will boot next, resolved through the same rule the launch uses —
   * "reset to the showcase" only reaches a showcase that exists.
   */
  clearDefault: (): Promise<string> => invoke<string>("project_clear_default"),
  close: (): Promise<void> => invoke("project_close"),
};

/**
 * Native OS shell integration (editor seams). `reveal` opens the platform file
 * browser at `path`, selecting the entry when it's a file. The backend validates
 * the path is inside the open project or app-data dir before shelling out.
 */
export const shell = {
  reveal: (path: string): Promise<void> => invoke("shell_reveal", { path }),
};

/** Project file surface (P5.4): read/write + a gitignore-aware listing. */
export const files = {
  read: (path: string): Promise<string> => invoke<string>("file_read", { path }),
  write: (path: string, content: string): Promise<void> =>
    invoke("file_write", { path, content }),
  list: (root: string): Promise<FileEntryDto[]> =>
    invoke<FileEntryDto[]>("list_project_files", { root }),
};

/** Git panel (P5.4): shells out to the `git` CLI. `repo` is the project root. */
export const git = {
  status: (repo: string): Promise<GitStatusDto> => invoke<GitStatusDto>("git_status", { repo }),
  stage: (repo: string, paths: string[]): Promise<void> => invoke("git_stage", { repo, paths }),
  unstage: (repo: string, paths: string[]): Promise<void> => invoke("git_unstage", { repo, paths }),
  discard: (repo: string, paths: string[]): Promise<void> => invoke("git_discard", { repo, paths }),
  commit: (repo: string, message: string): Promise<string> =>
    invoke<string>("git_commit", { repo, message }),
  fileDiff: (repo: string, path: string, staged: boolean): Promise<string> =>
    invoke<string>("git_file_diff", { repo, path, staged }),
  branches: (repo: string): Promise<string[]> => invoke<string[]>("git_branches", { repo }),
  init: (repo: string): Promise<void> => invoke("git_init", { repo }),
};

/** Global workspace search (P5.4). */
export const search = {
  workspace: (root: string, query: string, opts: SearchOptsDto): Promise<SearchHitDto[]> =>
    invoke<SearchHitDto[]>("search_workspace", { root, query, opts }),
};

/**
 * Language intelligence (P5.2): a rust-analyzer LSP client. `didOpen/didChange/
 * didClose` are fire-and-forget notifications; `request` pulls completion/hover/
 * definition; diagnostics arrive on the `lsp://diagnostics` event.
 */
export const lsp = {
  start: (language: string, workspace: string): Promise<void> =>
    invoke("lsp_start", { language, workspace }),
  stop: (language: string): Promise<void> => invoke("lsp_stop", { language }),
  didOpen: (language: string, path: string, text: string): Promise<void> =>
    invoke("lsp_did_open", { language, path, text }),
  didChange: (language: string, path: string, text: string): Promise<void> =>
    invoke("lsp_did_change", { language, path, text }),
  didClose: (language: string, path: string): Promise<void> =>
    invoke("lsp_did_close", { language, path }),
  // `params`/result are raw LSP JSON (opaque to the typed layer).
  request: (language: string, method: string, params: unknown): Promise<unknown> =>
    invoke<unknown>("lsp_request", { language, method, params }),
};

/**
 * InfiniScript (wave SCRIPT2b). One command, and it is the reason the frontend
 * never parses `.infini`: `check` hands a buffer to `inf_script::compile_bytes`
 * — the same file door the asset watcher, `inf cook` and the PIE payload
 * builder go through — and gets Ring 0's diagnostics back with their line,
 * column and length **as Ring 0 counts them** (1-based, characters). `path` is
 * a label only; nothing is read from disk. A file that will not compile is a
 * resolved promise carrying its refusals, never a rejection: refusals are
 * values (P21), across the IPC boundary as well as inside it.
 */
export const script = {
  check: (text: string, path?: string): Promise<ScriptDiagnosticDto[]> =>
    invoke<ScriptDiagnosticDto[]>("script_check", { text, path: path ?? null }),
  /**
   * The graph↔text bridge's editor half: a blueprint asset (`.inf_act` or
   * `.infini`) rendered as the `.infini` file it would be, through the Ring-0
   * emitter. Rejects — with the class named — when the IR has no written form.
   */
  emitClass: (assetId: string): Promise<string> =>
    invoke<string>("script_emit_class", { assetId }),
};

/**
 * Blueprint graphs (Phase 6). The visual node editor drives everything here:
 * fetch the palette, CRUD documents, apply edit batches (invariant-checked +
 * re-validated on the backend), run a graph through the interpreter, and read
 * the generated Rust. Types come from `./blueprintTypes` (mirrors of the
 * Ring-0 graph crate, not ts-rs). Edits are the kebab-case tagged union the
 * backend deserializes as `inf_graph::GraphEdit`.
 */
export const graph = {
  registry: (): Promise<NodeDef[]> => invoke<NodeDef[]>("graph_registry"),
  list: (): Promise<BpDoc[]> => invoke<BpDoc[]>("graph_list"),
  create: (name: string): Promise<BpDoc> => invoke<BpDoc>("graph_create", { name }),
  /**
   * **Open the blueprint OF an actor** (Wave E): decode the `.inf_act`, raise a
   * handler's IR back into a graph, and register it under the asset-keyed
   * document id `bp:<assetId>` (idempotent by asset, like `dcc_open`).
   *
   * Rejects with a named reason when the chosen handler — or the whole class —
   * is outside lowering's image and therefore has no unambiguous node form. The
   * reply lists EVERY handler with `raisable`/`reason` so the canvas can offer a
   * switcher rather than pretend an actor has one graph.
   */
  openActor: (assetId: string, handler: string | null = null): Promise<ActorGraphDto> =>
    invoke<ActorGraphDto>("graph_open_actor", { assetId, handler }),
  get: (id: string): Promise<BpDoc> => invoke<BpDoc>("graph_get", { id }),
  /** Free a document + its undo journal from the backend (leak fix). */
  close: (id: string): Promise<void> => invoke("graph_close", { id }),
  apply: (id: string, edits: BpEdit[], label: string): Promise<GraphApplyResult> =>
    invoke<GraphApplyResult>("graph_apply", { id, edits, label }),
  undo: (id: string): Promise<BpDoc | null> => invoke<BpDoc | null>("graph_undo", { id }),
  redo: (id: string): Promise<BpDoc | null> => invoke<BpDoc | null>("graph_redo", { id }),
  run: (id: string): Promise<GraphRunResult> => invoke<GraphRunResult>("graph_run", { id }),
  /**
   * B-P4 tier A: run the graph under debug lowering with `breakpoints` (canvas
   * node ids) and optional wire `capture`. Returns the hits (node ids), captured
   * wire values, logs, and final vars (run-to-completion trace, not a live pause).
   */
  debugRun: (id: string, breakpoints: number[], capture: boolean): Promise<DebugRunResult> =>
    invoke<DebugRunResult>("graph_debug_run", { id, breakpoints, capture }),
  generate: (id: string): Promise<string> => invoke<string>("graph_generate", { id }),
  /**
   * **The CODE TAB** (Wave D): write this class's generated Rust to
   * `<project>/src/blueprints/<Class>_<guid8>.rs` and answer with the path.
   *
   * Written on demand and on **staleness** — the file's banner carries the
   * graph's content hash, so a tab opened twice is one read and a canvas nudge
   * costs no filesystem write. `wrote: false` means it was already current.
   */
  writeSource: (id: string): Promise<GeneratedSourceDto> =>
    invoke<GeneratedSourceDto>("graph_write_source", { id }),
};

/**
 * Material graphs (Phase 7.2). Mirrors the blueprint surface (CRUD + apply +
 * undo/redo over the shared `inf-graph` shapes), plus `compile`: the material
 * node graph → naga-validated WGSL, node-anchored diagnostics, and an offscreen
 * preview-sphere render (PNG data-URL). Documents share the `BpDoc`/`BpEdit`
 * shapes; only the compile result is material-specific.
 */
/**
 * **The Model Editor** (P23.4). One document per `.inf_mesh` asset, keyed
 * `"dcc:<assetId>"`.
 *
 * Two things about this surface are load-bearing and easy to get wrong from the
 * frontend:
 *
 * 1. **`pick` and `preview` must be given the SAME `size`.** The camera lives in
 *    the backend document and the projection is built from the size, so a pick
 *    computed at one size against an image rendered at another lands somewhere
 *    else. `DCC_PREVIEW_SIZE` is the one number both use.
 * 2. **Every mutating call returns the document**, because a modelling op moves
 *    the journal's generation stamp and may therefore have DROPPED the selection
 *    (ids are arena slots; a structural op renumbers). The store replaces its
 *    state from the returned doc rather than patching it.
 */
export const dcc = {
  /** Open (or re-attach to) a mesh asset. Idempotent. */
  open: (assetId: string): Promise<DccDocDto> => invoke<DccDocDto>("dcc_open", { assetId }),
  /**
   * **Start a new model** (Wave D): mint a `.inf_mesh` from a kernel primitive,
   * open a session on it, and reveal it in the drawer.
   *
   * Not idempotent, and cannot be: every call is a new asset. The panel's dialog
   * is what stops a stray press from filling `Content/Meshes` with cubes.
   */
  new: (spec: DccNewDto): Promise<DccDocDto> => invoke<DccDocDto>("dcc_new", { spec }),
  /**
   * Free a document, **by asset id**. Symmetric with `open`, and deliberately so:
   * a panel that unmounts before its `open` resolves has no document id yet, and
   * a close it cannot send is a leaked backend session. Idempotent.
   */
  close: (assetId: string): Promise<void> => invoke("dcc_close", { assetId }),
  list: (): Promise<DccDocDto[]> => invoke<DccDocDto[]>("dcc_list"),
  /** Press a tool against the current selection. A refusal is a value, not a throw. */
  apply: (id: string, tool: DccToolDto): Promise<DccApplyDto> =>
    invoke<DccApplyDto>("dcc_apply", { id, tool }),
  select: (id: string, action: DccSelectDto): Promise<DccDocDto> =>
    invoke<DccDocDto>("dcc_select", { id, action }),
  /** Pointer → component. `size` must match the last `preview` size. */
  pick: (id: string, x: number, y: number, size: number, additive: boolean): Promise<DccDocDto> =>
    invoke<DccDocDto>("dcc_pick", { id, x, y, size, additive }),
  /**
   * **Marquee select** (Wave D). Same `size` rule as `pick`, for the same
   * reason: the projection is built from it backend-side.
   *
   * A rectangle under two pixels either way is a click that wobbled and is a
   * no-op — clearing a whole selection because a hand moved is worse than
   * missing a tiny marquee.
   */
  boxSelect: (
    id: string,
    x0: number,
    y0: number,
    x1: number,
    y1: number,
    size: number,
    additive: boolean,
  ): Promise<DccDocDto> =>
    invoke<DccDocDto>("dcc_box_select", { id, x0, y0, x1, y1, size, additive }),
  /**
   * Set the gizmo's pivot, its axis orientation, and the x-ray toggle. Every
   * argument is optional; `null` means "leave it".
   */
  setViewOpts: (
    id: string,
    opts: { pivot?: DccPivotDto; orient?: DccOrientDto; xray?: boolean },
  ): Promise<DccDocDto> =>
    invoke<DccDocDto>("dcc_set_view_opts", {
      id,
      pivot: opts.pivot ?? null,
      orient: opts.orient ?? null,
      xray: opts.xray ?? null,
    }),
  /** Orbit (degrees) and dolly (a proportion, so it scales with the model). */
  orbit: (id: string, yawDeg: number, pitchDeg: number, dolly: number): Promise<void> =>
    invoke("dcc_orbit", { id, yawDeg, pitchDeg, dolly }),
  frame: (id: string): Promise<void> => invoke("dcc_frame", { id }),
  undo: (id: string): Promise<DccDocDto> => invoke<DccDocDto>("dcc_undo", { id }),
  /**
   * **The history**, as rows — the op list the Edit menu has advertised since
   * Phase 1 and never had behind it. The whole journal, redo tail included.
   */
  history: (id: string): Promise<DccHistoryEntryDto[]> =>
    invoke<DccHistoryEntryDto[]>("dcc_history", { id }),
  /**
   * **Re-parameterize an edit that is already in the past**, and re-derive
   * everything after it — the wave's signature capability.
   *
   * A refusal is a value: the reply carries `ok: false` and a reason, and the
   * session is byte-identical.
   */
  amend: (id: string, index: number, value: number): Promise<DccApplyDto> =>
    invoke<DccApplyDto>("dcc_amend", { id, index, value }),
  redo: (id: string): Promise<DccDocDto> => invoke<DccDocDto>("dcc_redo", { id }),
  /**
   * One offscreen frame as a PNG data-URL, with the overlay composited in.
   *
   * `hover` is `[x, y, radiusM]` in the preview's own pixel space and metres —
   * the **hover brush ring** (Wave D). Sent only while a brush tool is armed and
   * the pointer is over the image, because it costs a frame per pointer-move:
   * the same cost as an orbit frame, which the panel already pays.
   */
  preview: (
    id: string,
    size: number,
    hover?: [number, number, number] | null,
  ): Promise<DccPreviewDto> =>
    invoke<DccPreviewDto>("dcc_preview", { id, size, hover: hover ?? null }),
  /** Write the mesh back to its asset (rewrite + synchronous vmesh derive). */
  save: (id: string): Promise<DccSaveDto> => invoke<DccSaveDto>("dcc_save", { id }),
  /** Drop another mesh asset in as a second component. */
  mergeAsset: (id: string, assetId: string): Promise<DccApplyDto> =>
    invoke<DccApplyDto>("dcc_merge_asset", { id, assetId }),

  // ── P24.4 cloth & hair authoring ────────────────────────────────────────
  //
  // Both take their OPERAND from the document's own selection, backend-side —
  // the vertex selection is the garment's pin list, the face selection is the
  // hairstyle's scalp — so the panel sends knobs and never a component list.
  // Both refuse as a VALUE (`ok: false` + `refusal`), never by throwing.

  /** Turn the open mesh into a `.inf_cloth`; the selected vertices are pinned. */
  makeGarment: (id: string, spec: DccGarmentDto): Promise<DccGroomResultDto> =>
    invoke<DccGroomResultDto>("dcc_make_garment", { id, spec }),
  /** Grow guides out of the selected faces into a `.inf_hair`. */
  growHair: (id: string, spec: DccGroomDto): Promise<DccGroomResultDto> =>
    invoke<DccGroomResultDto>("dcc_grow_hair", { id, spec }),

  // ── pointer drags (P23.5): the sculpt brush and the component gizmo ──────
  //
  // One triple for both gestures, because they ARE one gesture with different
  // arithmetic. The backend holds the drag; the panel owes it an `end` (or a
  // `cancel`) — and if the panel disappears mid-drag, every other backend door
  // settles the orphan rather than dropping it.

  /** Arm or disarm the transform gizmo (`null` hides the handles). */
  setGizmo: (id: string, mode: DccGizmoModeDto | null): Promise<DccDocDto> =>
    invoke<DccDocDto>("dcc_set_gizmo", { id, mode }),
  /**
   * Start a drag. `grabbed: false` means the pointer found neither the surface
   * nor a handle — **not** an error: it is the panel's cue to orbit instead,
   * which is what lets one button paint on the model and orbit off it.
   */
  dragBegin: (
    id: string,
    drag: DccDragDto,
    x: number,
    y: number,
    size: number,
  ): Promise<DccDragBeginDto> =>
    invoke<DccDragBeginDto>("dcc_drag_begin", { id, drag, x, y, size }),
  /** Extend the drag. Returns nothing: the next `preview` is what shows it. */
  dragMove: (id: string, x: number, y: number, size: number): Promise<void> =>
    invoke("dcc_drag_move", { id, x, y, size }),
  /** Finish the drag — ONE journal entry for the whole gesture. */
  dragEnd: (id: string): Promise<DccApplyDto> => invoke<DccApplyDto>("dcc_drag_end", { id }),
  /** Throw the drag away (Escape). The author's explicit "no". */
  dragCancel: (id: string): Promise<DccDocDto> => invoke<DccDocDto>("dcc_drag_cancel", { id }),

  // ── UV (P23.5) ──────────────────────────────────────────────────────────

  /**
   * Cut at the seams, solve, pack, and journal the RESULT as one op.
   *
   * `worstResidual` is the honest half: the solver runs a fixed iteration count,
   * so a big number means a distorted chart the author can fix by adding a seam
   * — not a failure, and not something to hide behind "unwrap complete".
   */
  unwrap: (id: string): Promise<DccUnwrapDto> => invoke<DccUnwrapDto>("dcc_unwrap", { id }),
  /**
   * One frame of the 2D UV view. CPU-composited like the 3D overlay and for the
   * same reason: seams, charts and the selection are backend facts, and a second
   * renderer would be a second answer to them.
   */
  uvPreview: (id: string, size: number): Promise<DccPreviewDto> =>
    invoke<DccPreviewDto>("dcc_uv_preview", { id, size }),
  /**
   * **Pick in the UV pane** (Wave D). Answers with the whole document, because a
   * UV pick changes the SHARED selection — the 3D view lights up too, which is
   * the point of one selection and two pictures.
   */
  uvPick: (
    id: string,
    x: number,
    y: number,
    size: number,
    additive: boolean,
  ): Promise<DccDocDto> => invoke<DccDocDto>("dcc_uv_pick", { id, x, y, size, additive }),
  /**
   * **Drag the selection in UV space.** `dx`/`dy` are pane pixels; a drag of
   * `size` pixels is one whole UV unit. One journal entry per gesture.
   */
  uvMove: (id: string, dx: number, dy: number, size: number): Promise<DccApplyDto> =>
    invoke<DccApplyDto>("dcc_uv_move", { id, dx, dy, size }),
};

/**
 * The preview edge length, used by BOTH `dcc.preview` and `dcc.pick`.
 *
 * 256 because the P23.2a measurement says the render is free (0.09 ms) and the
 * transport is not: 512² is ~1.4 MB of base64 a frame, ~42 MB/s through the
 * webview bridge at 30 fps.
 */
export const DCC_PREVIEW_SIZE = 256;

/**
 * The most profile segments one bevel may cut — mirrors
 * `inf_dcc::MAX_BEVEL_SEGMENTS`.
 *
 * A **mirror**, not a source of truth: the kernel refuses anything outside
 * `1..=16` as a typed value, so a frontend that drifted past it would get a
 * refusal with a message rather than a bad mesh. The number is here so the
 * spinner stops where the tool stops instead of collecting a refusal per press.
 */
export const MAX_BEVEL_SEGMENTS = 16;

export const material = {
  registry: (): Promise<NodeDef[]> => invoke<NodeDef[]>("material_registry"),
  list: (): Promise<BpDoc[]> => invoke<BpDoc[]>("material_list"),
  create: (name: string): Promise<BpDoc> => invoke<BpDoc>("material_create", { name }),
  get: (id: string): Promise<BpDoc> => invoke<BpDoc>("material_get", { id }),
  /** Free a document + its undo journal from the backend (leak fix). */
  close: (id: string): Promise<void> => invoke("material_close", { id }),
  apply: (id: string, edits: BpEdit[], label: string): Promise<GraphApplyResult> =>
    invoke<GraphApplyResult>("material_apply", { id, edits, label }),
  undo: (id: string): Promise<BpDoc | null> => invoke<BpDoc | null>("material_undo", { id }),
  redo: (id: string): Promise<BpDoc | null> => invoke<BpDoc | null>("material_redo", { id }),
  compile: (id: string): Promise<MaterialCompileResult> =>
    invoke<MaterialCompileResult>("material_compile", { id }),
  /** Bake the graph to a new `.inf_tex` asset via a compute pass; returns the id. */
  bake: (id: string, size: number, name: string): Promise<string> =>
    invoke<string>("material_bake", { id, size, name }),
};

/**
 * PCG graphs (Phase 10.5b). Mirrors the material surface (CRUD + apply +
 * undo/redo over the shared `inf-graph` shapes), plus `compile` (lower the graph
 * to the runtime `PcgDocument` + node-anchored diagnostics), `save` (persist the
 * graph into a `.inf_pcg` asset), and `evaluate` (scatter over the scene terrain
 * into the selected `PcgVolume`, refreshing the viewport). Documents share the
 * `BpDoc`/`BpEdit` shapes; only the compile/evaluate results are PCG-specific.
 */
export const pcg = {
  registry: (): Promise<NodeDef[]> => invoke<NodeDef[]>("pcg_registry"),
  list: (): Promise<BpDoc[]> => invoke<BpDoc[]>("pcg_list"),
  create: (name: string): Promise<BpDoc> => invoke<BpDoc>("pcg_create", { name }),
  get: (id: string): Promise<BpDoc> => invoke<BpDoc>("pcg_get", { id }),
  /** Free a document + its undo journal from the backend (leak fix). */
  close: (id: string): Promise<void> => invoke("pcg_close", { id }),
  apply: (id: string, edits: BpEdit[], label: string): Promise<GraphApplyResult> =>
    invoke<GraphApplyResult>("pcg_apply", { id, edits, label }),
  undo: (id: string): Promise<BpDoc | null> => invoke<BpDoc | null>("pcg_undo", { id }),
  redo: (id: string): Promise<BpDoc | null> => invoke<BpDoc | null>("pcg_redo", { id }),
  compile: (id: string): Promise<PcgCompileResult> =>
    invoke<PcgCompileResult>("pcg_compile", { id }),
  /** Persist the graph to a `.inf_pcg` asset; returns the written file name. */
  save: (id: string, name: string): Promise<string> => invoke<string>("pcg_save", { id, name }),
  /** Scatter over the scene terrain into the target volume (null → selection). */
  evaluate: (id: string, entity: string | null): Promise<PcgEvaluateResult> =>
    invoke<PcgEvaluateResult>("pcg_evaluate", { id, entity }),
  /** Run a terrain's biome→PCG binding (P19.3): each painted biome's own graph
   *  over the region its id owns (null → the first terrain with a biome set).
   *  Independent of the open document — the graphs come from the biome set. */
  evaluateBiomes: (entity: string | null): Promise<PcgBiomeResult> =>
    invoke<PcgBiomeResult>("pcg_evaluate_biomes", { entity }),
};

/**
 * Animation State Machines (P11.2). Unlike the graph editors, a state machine is
 * a plain typed model (states + transitions), so there is no registry / apply /
 * undo surface — the frontend owns the document and pushes the whole thing back
 * on `save` (which writes a `.inf_sm` asset). `listClips` enumerates the imported
 * `.inf_anim` clips a state's Clip motion can point at.
 */
export const sm = {
  list: (): Promise<SmDoc[]> => invoke<SmDoc[]>("sm_list"),
  create: (name: string): Promise<SmDoc> => invoke<SmDoc>("sm_create", { name }),
  get: (id: string): Promise<SmDoc> => invoke<SmDoc>("sm_get", { id }),
  /** Free a document from the backend workspace (leak fix). */
  close: (id: string): Promise<void> => invoke("sm_close", { id }),
  /** Persist `doc` to a `.inf_sm` asset; returns the written file name. */
  save: (id: string, doc: SmDoc, name: string): Promise<string> =>
    invoke<string>("sm_save", { id, doc, name }),
  listClips: (): Promise<SmClipDto[]> => invoke<SmClipDto[]>("sm_list_clips"),
  /**
   * **Propose a machine over a clip set** (P29.5, pillar S3). Returns an
   * ordinary `SmMachineDto` plus the reasoning that produced it; nothing is
   * written, and the author saves it through `save` like any other document.
   */
  propose: (clips: string[]): Promise<SmProposalDto> =>
    invoke<SmProposalDto>("sm_propose", { clips }),
};

/**
 * Animation clip derivation (P29.5, pillar S2). `clipInfo` reads a `.inf_anim`
 * back -- its curve channels with a sparkline each, its markers, and its baked
 * root motion -- so a panel shows what the import measured rather than asserting
 * that it exists. `rederive` runs the derivation again over a clip on disk,
 * which is safe on a button because the rule un-bakes before it bakes.
 */
export const anim = {
  clipInfo: (id: string): Promise<AnimClipInfoDto> =>
    invoke<AnimClipInfoDto>("anim_clip_info", { id }),
  rederive: (id: string, traversal: boolean): Promise<AnimDeriveDto> =>
    invoke<AnimDeriveDto>("anim_rederive", { id, traversal }),
};

/**
 * Blend-space authoring geometry (P29.2). **Stateless** — the panel owns the
 * sample list and hands the whole thing over on every change, which is what lets
 * the same command serve the editing canvas and a future preview without a
 * backend document to keep in step.
 *
 * `preview` returns everything the canvas draws in one round trip: the Delaunay
 * triangulation, its hull, the barycentric weights at the query point, the
 * weight-blended cycle length, and the blended pose's joints. It is the engine's
 * own `inf_anim::delaunay` / `sample_blend_space_2d` — deliberately not a
 * TypeScript re-implementation, because these weights are sim state and a second
 * implementation is free to disagree.
 */
export const blendSpace = {
  preview: (
    samples: BlendSampleDto[],
    x: number,
    y: number,
    timeS: number,
  ): Promise<BlendPreviewDto> =>
    invoke<BlendPreviewDto>("blendspace_preview", { samples, x, y, timeS }),
};

/**
 * Skeleton templates (P24.1). One door: generate a parametric N-pedal rig and
 * write it as a `.inf_skel` under `Content/Skeletons`, returning the new asset
 * GUID. `plan` is one of `biped` / `quadruped` / `hexapod` / `npedal` (the last
 * needs `legs`); everything the caller does not set comes from the generator's
 * default proportions. Full proportion editing is the P24.5 wizard's job — this
 * is the create door, not a skeleton editor.
 */
export const skel = {
  createTemplate: (
    plan: BodyPlanName,
    opts: { legs?: number; heightM?: number; name?: string } = {},
  ): Promise<string> =>
    invoke<string>("skel_create_template", {
      plan,
      legs: opts.legs ?? null,
      heightM: opts.heightM ?? null,
      name: opts.name ?? null,
    }),

  // ── the Skeleton Editor (P24.3) ───────────────────────────────
  //
  // The document key is the **asset GUID** — not a `"skel:<id>"` composite —
  // because a skeleton session owns nothing the asset does not, so re-opening a
  // rig returns the live document. `close` takes the same key for the reason
  // `dcc.close` does: a panel that unmounts before its `open` resolves has no
  // other id to close with, and a close it cannot send is a leaked session.
  //
  // **Every mutating call returns the whole document.** A rename or a template
  // instantiation can renumber or replace every joint, so the store REPLACES its
  // state rather than patching it — the `dcc` rule, for the same reason.

  /** Open (or re-attach to) a skeleton asset. Idempotent. */
  open: (assetId: string): Promise<SkelDocDto> =>
    invoke<SkelDocDto>("skel_open", { assetId }),
  /** Free the document and its undo history. Idempotent. */
  close: (assetId: string): Promise<void> => invoke("skel_close", { assetId }),
  list: (): Promise<SkelDocDto[]> => invoke<SkelDocDto[]>("skel_list"),

  /**
   * Rename a joint. A rename that leaves the canonical humanoid vocabulary, or
   * breaks a left/right pair, still HAPPENS and comes back with a `warning` —
   * refusing would make the editor unable to author a non-humanoid.
   */
  renameJoint: (id: string, joint: number, name: string): Promise<SkelApplyDto> =>
    invoke<SkelApplyDto>("skel_rename_joint", { id, joint, name }),
  /**
   * Move a joint's **rest** transform. Every inverse bind is recomputed by the
   * backend — not optional: a stale one deforms every mesh bound to the rig.
   */
  setJointTransform: (
    id: string,
    joint: number,
    translation: [number, number, number],
    rotation: [number, number, number, number],
    scale: [number, number, number],
  ): Promise<SkelApplyDto> =>
    invoke<SkelApplyDto>("skel_set_joint_transform", {
      id,
      joint,
      translation,
      rotation,
      scale,
    }),
  /**
   * Set or clear a joint's rotation limit. Passing `null` for either bound
   * **clears the row** — absent means unlimited, and a full-range row would be a
   * different (authored) statement.
   */
  setLimit: (
    id: string,
    joint: number,
    minDeg: [number, number, number] | null,
    maxDeg: [number, number, number] | null,
  ): Promise<SkelApplyDto> =>
    invoke<SkelApplyDto>("skel_set_limit", { id, joint, minDeg, maxDeg }),

  addSocket: (id: string, name: string, joint: number): Promise<SkelApplyDto> =>
    invoke<SkelApplyDto>("skel_add_socket", { id, name, joint }),
  removeSocket: (id: string, name: string): Promise<SkelApplyDto> =>
    invoke<SkelApplyDto>("skel_remove_socket", { id, name }),
  placeSocket: (
    id: string,
    name: string,
    joint: number,
    translation: [number, number, number],
    rotation: [number, number, number, number],
    scale: [number, number, number],
  ): Promise<SkelApplyDto> =>
    invoke<SkelApplyDto>("skel_place_socket", {
      id,
      name,
      joint,
      translation,
      rotation,
      scale,
    }),

  /** **Replace** the rig with a fresh template. Undoable, like every other edit. */
  instantiateTemplate: (
    id: string,
    plan: BodyPlanName,
    opts: { legs?: number; heightM?: number } = {},
  ): Promise<SkelApplyDto> =>
    invoke<SkelApplyDto>("skel_instantiate_template", {
      id,
      plan,
      legs: opts.legs ?? null,
      heightM: opts.heightM ?? null,
    }),
  /**
   * Append another rig onto this one at `attach` — modular rigging. Base joint
   * indices never move, so an IK chain authored on this rig survives; the
   * `warning` carries the offset a merged part's weight table needs.
   */
  mergePart: (id: string, partAsset: string, attach: number): Promise<SkelApplyDto> =>
    invoke<SkelApplyDto>("skel_merge_part", { id, partAsset, attach }),

  undo: (id: string): Promise<SkelApplyDto> => invoke<SkelApplyDto>("skel_undo", { id }),
  redo: (id: string): Promise<SkelApplyDto> => invoke<SkelApplyDto>("skel_redo", { id }),
  /** Write the rig back to its `.inf_skel`. Dirty is cleared only on success. */
  save: (id: string): Promise<SkelApplyDto> => invoke<SkelApplyDto>("skel_save", { id }),

  /**
   * **Auto-fit a template into a mesh** and replace this rig with the result —
   * one undoable edit. The `warning` carries the fit report (measured height, how
   * many joints landed inside the mesh, symmetry, rejected steps), because a fit
   * that placed most joints outside is one an author needs to see.
   */
  fitToMesh: (
    id: string,
    meshAsset: string,
    plan: BodyPlanName,
    opts: { legs?: number; heightM?: number } = {},
  ): Promise<SkelApplyDto> =>
    invoke<SkelApplyDto>("skel_fit_to_mesh", {
      id,
      meshAsset,
      plan,
      legs: opts.legs ?? null,
      heightM: opts.heightM ?? null,
    }),
};

/**
 * The body plans the generator offers.
 *
 * A string union mirroring the backend's `parse_plan`, deliberately not a
 * generated ts-rs enum: the backend's own comment says the plan set is the one
 * part of this API expected to grow, and a name it does not know fails loudly
 * with the list of what it does.
 */
export type BodyPlanName =
  | "biped"
  | "biped-canonical"
  | "quadruped"
  | "hexapod"
  | "npedal";

/**
 * **New Character from Template** (P24.5) — the wizard's two doors.
 *
 * `preview` writes nothing and is called on every edit, so a refusal comes back
 * INSIDE the DTO (`refusal` set, `rig` null) rather than as a rejected promise:
 * half the intermediate states of a proportion drag are invalid and an error
 * toast per keystroke is not a wizard. `create` is the explicit action and does
 * reject, because by then the user has pressed a button.
 */
export const character = {
  /** What this spec would produce. Writes nothing. */
  preview: (spec: CharacterSpecDto): Promise<CharacterPreviewDto> =>
    invoke<CharacterPreviewDto>("character_preview", { spec }),

  /**
   * Generate the rig, body, three clips and the state machine under
   * `Content/<folder>`, and optionally add a ready actor to the open level.
   * `at` is the actor's world position in **metres** (units doctrine).
   */
  create: (
    spec: CharacterSpecDto,
    opts: { addToScene?: boolean; at?: [number, number, number] } = {},
  ): Promise<CharacterCreateDto> =>
    invoke<CharacterCreateDto>("character_create", {
      spec,
      addToScene: opts.addToScene ?? false,
      at: opts.at ?? null,
    }),

  /**
   * Place the COMMITTED starter character (wave GTA1). Writes no assets -- it
   * spawns an actor wearing the seventeen files every 3D project ships with,
   * which is what `create` above does not do (it mints six new ones every call).
   * Resolves to the new actor's guid; one undo step, and it is selected.
   */
  placeStarter: (
    at?: [number, number, number],
    female?: boolean,
  ): Promise<string> =>
    invoke<string>("character_place_starter", {
      at: at ?? null,
      female: female ?? null,
    }),

  /** The content sub-folder generated characters land in. */
  folder: (): Promise<string> => invoke<string>("character_folder"),
};

/**
 * The capture wizard (P25.4): photographs -> reconstruct with progress ->
 * preview through the offscreen path -> import.
 *
 * One session per process. `load` and `setSettings` are cheap and reconstruct
 * nothing; `start` and `refinish` return immediately and report on
 * `photogrammetry://progress` (see lib/events.ts). Everything that can refuse
 * refuses before a run begins, so a rejected promise here is a pre-flight, not
 * a solver.
 *
 * UNITS: `metresPerUnit` is the SCALE STEP — metres per reconstruction unit.
 * `1.0` leaves the result in the reconstruction's own baseline units, which is
 * honest rather than metric (structure from motion is scale-ambiguous).
 */
export const photogrammetry = {
  /** The whole panel state. Cheap; call it after anything that changes it. */
  status: (): Promise<CaptureStatusDto> => invoke<CaptureStatusDto>("photo_status"),

  /** Load a photograph set, replacing whatever was loaded. Runs the pre-flight. */
  load: (paths: string[]): Promise<CaptureStatusDto> =>
    invoke<CaptureStatusDto>("photo_load", { paths }),

  /** Replace the settings. Takes effect on the next `start` or `refinish`. */
  setSettings: (settings: CaptureSettingsDto): Promise<CaptureStatusDto> =>
    invoke<CaptureStatusDto>("photo_set_settings", { settings }),

  /** Start a reconstruction. Rejects when the pre-flight blocks. */
  start: (): Promise<CaptureStatusDto> => invoke<CaptureStatusDto>("photo_start"),

  /**
   * Re-run the FINISH stage alone over the reconstruction already in hand — how
   * the scale step, the triangle budget and the atlas size are changed without
   * paying for structure from motion and the dense solve again.
   */
  refinish: (): Promise<CaptureStatusDto> => invoke<CaptureStatusDto>("photo_refinish"),

  /**
   * Ask an in-flight run to stop. Resolves to whether one was running.
   *
   * It stops BETWEEN stages: a stage is one blocking solve, so Cancel during a
   * dense pass lands when that pass returns — and `finish` is the last automatic
   * stage, so a Cancel that lands inside IT finds nothing left to skip and the
   * run completes into `ready`. Nothing is written either way.
   */
  cancel: (): Promise<boolean> => invoke<boolean>("photo_cancel"),

  /** Forget the photographs, the reconstruction and the state. */
  reset: (): Promise<CaptureStatusDto> => invoke<CaptureStatusDto>("photo_reset"),

  /**
   * Preview the finished scan: the geometry rendered offscreen, the baked base
   * colour beside it. Either may be absent — the render needs a GPU adapter and
   * the atlas does not.
   */
  preview: (yaw: number, pitch: number, size?: number): Promise<CapturePreviewDto> =>
    invoke<CapturePreviewDto>("photo_preview", { yaw, pitch, size: size ?? null }),

  /** Write the five assets under `Content/<folder>` and re-sync the drawer. */
  import: (name: string): Promise<CaptureImportDto> =>
    invoke<CaptureImportDto>("photo_import", { name }),
};

/**
 * Cook / Package (P9.2 item 3). Runs `inf_packager::cook` against the open
 * project on a blocking task and resolves to a `PackageResultDto`, or **rejects
 * with a structured `PackageErrorDto`** (blueprint failures carry the class +
 * handler anchor). Start/finish also broadcasts on `package://state`. Arg names
 * are camelCase (Tauri maps to snake_case); `outDir` defaults to `<project>/Build`
 * and `roots` (asset GUIDs) to the default root set.
 */
export const packaging = {
  cook: (outDir: string | null = null, roots: string[] | null = null): Promise<PackageResultDto> =>
    invoke<PackageResultDto>("project_package", { outDir, roots }),
};

/**
 * In-editor Simulate / Play (P8.4). Drives the `SimSession` over the live
 * `SceneDoc`: `start` snapshots the world + fires BeginPlay, `tick` advances one
 * frame with the currently-held **physical keys** (the backend owns both the
 * binding table and the fixed-step accumulation), `stop` restores the pre-play
 * world exactly. Running state also broadcasts on the `sim://state` event (see
 * lib/events.ts).
 */
export const sim = {
  /** Enter Simulate over the current scene. Rejects (e.g. no scene) with a message. */
  start: (): Promise<void> => invoke("sim_start"),
  /**
   * Advance one frame with the currently-held **physical keys**
   * (`KeyboardEvent.code` values, e.g. `["KeyW","Shift"]`) — the backend
   * resolves them through `inf_input::default_map`, which is the same table the
   * shipped player reads. Resolves to whether a session was running (false =
   * no-op). Arg name is camelCase.
   */
  tick: (keys: string[]): Promise<boolean> => invoke<boolean>("sim_tick", { keys }),
  /**
   * Advance **exactly one fixed step** with the held physical keys (B-P4 tier
   * A′):
   * bypasses the wall-clock accumulator, so Step is a guaranteed single step.
   * Resolves to whether a session was running.
   */
  stepFixed: (keys: string[]): Promise<boolean> => invoke<boolean>("sim_step_fixed", { keys }),
  /**
   * Install the debugger config for an actor class (B-P4 tier A′): breakpoints
   * (IR `LocalId`s for hand-built classes) + wire capture. When a step hits a
   * breakpoint the backend emits `sim://debug`. No-op if no session is running.
   */
  setDebug: (classId: string, breakpoints: number[], capture: boolean): Promise<void> =>
    invoke("sim_set_debug", { classId, breakpoints, capture }),
  /**
   * **Queue a live tuning edit** (P29.5, pillar S4). It applies at the top of
   * the NEXT fixed step, never inside one. `kind` is `"field"` (a reflected
   * component field -- `typePath` defaults to `CharacterMovement`), `"param"` (a
   * machine parameter), `"trigger"` (a machine trigger; `value` is ignored),
   * `"vehicle"` (a raycast vehicle's spring/engine/grip tunables, by the chassis
   * guid) or `"camera"` (the locomotion camera's table; it has no entity, so
   * pass a nil guid). `keep` chooses whether the value survives Stop as an
   * ordinary undoable edit, and is ignored by the three kinds with no document
   * field to keep it on. Resolves to whether a session was running -- `false` is
   * a value, not an error, because a tuning panel is live over a session the
   * author can stop.
   */
  tune: (
    kind: "field" | "param" | "trigger" | "vehicle" | "camera" | "weapon",
    guid: string,
    name: string,
    value: number,
    keep: boolean,
    typePath?: string,
  ): Promise<boolean> =>
    invoke<boolean>("sim_tune", { kind, guid, name, value, keep, typePath: typePath ?? null }),
  /** Exit Simulate, restoring the pre-play world. */
  stop: (): Promise<void> => invoke("sim_stop"),
  /** Whether a Simulate session is currently running (mount-time sync). */
  isRunning: (): Promise<boolean> => invoke<boolean>("sim_is_running"),
};

/**
 * Play-In-Editor (P9.4). Spawns `inf-player` as a crash-isolated subprocess and
 * streams the **live** scene (unsaved edits included) to it — the same content
 * path a shipped game uses. `start` mode is `"embedded"` (reparent the player
 * window into the viewport, Windows) or `"window"` ("Play in New Window",
 * always works). Session state broadcasts on `pie://state`.
 */
export const pie = {
  /** Start PIE in the given mode; resumes if already paused. */
  start: (mode: "embedded" | "window"): Promise<void> => invoke("pie_start", { mode }),
  /** Pause the running player. */
  pause: (): Promise<void> => invoke("pie_pause"),
  /** Resume a paused player. */
  resume: (): Promise<void> => invoke("pie_resume"),
  /** Advance exactly one fixed step (while paused). */
  step: (): Promise<void> => invoke("pie_step"),
  /** Release input possession back to the editor (v1 Eject). */
  eject: (): Promise<void> => invoke("pie_eject"),
  /** Stop PIE: kill the player, restore the viewport. */
  stop: (): Promise<void> => invoke("pie_stop"),
  /** Whether a PIE session is running (mount-time sync). */
  isRunning: (): Promise<boolean> => invoke<boolean>("pie_is_running"),
};
